### PR TITLE
ESHOP website 

### LINKED ISSUE #963: ESHOP WEBSITE CLONE
**Describe the project you want to add with tech stack**

using html and css cloning website and adding certain new features like background video or audio ,forms and all

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by anjaliSilawat**
ESHOP Website  
Close #963

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by anjaliSilawat** [comment]
Hey @pranjay-poddar can you please look into this

**Comment by anjaliSilawat** [comment]
Hey @pranjay-poddar can you please review it and merge this

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Move your project from root to frontend projects folder

**Comment by MohitGupta121** [comment]
Inactive

**Pull request closed without merging**
