### PR TITLE
Weather forecasting app added under Js-project folder name

### LINKED ISSUE #1372: add a new weather forecasting website
Hi @pranjay-poddar ,
i would like to contribute web-based project on weather forecasting, please assign me.
**Describe the project you want to add with tech stack**
A weather app that Fetch data from the OpenWeatherMap API to allow users to search for and view the forecast in cities worldwide
tech stack used Html, CSS, Js, Api(OpenWeatherMap Api )

**Expected behaviour**

- 

**Screenshots (optional)**

Screenshot (154)
Screenshot (155)

**Additional context (optional )**

also please add gssoc tag, as I am contributing under the Girlscript summer of code Gssoc23.
Thank you!

### PR DESCRIPTION
**Pull request by gulshanjakhon**
# Title and Issue number 

add a new weather forecasting website #1372

Close #1372 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by gulshanjakhon** [comment]
also please assign gssoc-23 label
thank you

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@gulshanjakhon please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by gulshanjakhon** [comment]
yaa sure.

**Comment by gulshanjakhon** [comment]
Hi @MohitGupta121 please review again I have added a demo video

https://github.com/pranjay-poddar/Dev-Geeks/assets/72978519/e549a91e-44ee-4ed4-91b8-c50f56c46c49

Thank you
Gssoc23 contributor

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
