### PR TITLE
rename instragram to instagram and rename files name #2329

### LINKED ISSUE #2329: Typing mistake in repo "Dev-Geeks/Frontend-Projects /Instragram Clone"
**Describe the bug**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by soubhik-111**
# Title and Issue number 

rename instragram to instagram and rename files name #2329

Close #2329 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented in the code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by soubhik-111** [comment]
Hello @MohitGupta121,
Kindly review it 
I have raised the issue number 2329.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@soubhik-111 remove all those images from PR and use these images with the help of links. Upload images in anywhere and then use them in your Project. Thanks!

**Comment by soubhik-111** [comment]
@MohitGupta121 
It's not my project I have mentioned that there is a spelling mistake in name of the files and folder of one's project 
Can we merge this as it is for now?
As images are already present in main repo directory

**Comment by MohitGupta121** [comment]
@soubhik-111 but it's good to improve now move them If your are doing.

**Comment by soubhik-111** [comment]
Okay, I will move them then we'll ask for a review.

**Comment by soubhik-111** [comment]
@MohitGupta121 
Review it
It's really a good idea.
It takes 1 hour to do this.
Have learnt the implementation
Thanks

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
