### PR TITLE
GUESS THE FINGERS GAME

### LINKED ISSUE #1732: GAME-  GUESS THE FINGERS
**Describe the project you want to add with tech stack**
This game is about guessing the finger. the user have to guess weather 1,2,3,etc
**Expected behavior**
i am using math.random to make this project.  
using : 
HTML CSS JS
** Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Sushilverma002**
GUESS THE FINGERS GAMES and ISSUE #1732 
GAME IS CREATED AND ISSUE IS SOLVED.
ISSUE NO IS ALSO ADDED.

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/e48facf0-5b4e-48ee-b30b-80a755b90d6f

Close #1732 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Sushilverma002** [comment]
please review.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Sushilverma002 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Sushilverma002** [comment]
UPDATED.

**Review by MohitGupta121 — APPROVED** [review]
Thanks @Sushilverma002 Lgtm

**Pull request merged**
