### PR TITLE
removed conio.h header

### LINKED ISSUE #1961: Incompatibility Issue with 'conio.h' Header in C Program.
Description:
I have come across a C file that includes the "conio.h" header, but I'm facing issues when compiling the code. It seems that the "conio.h" header is not available or compatible with my current C compiler.

Steps to Reproduce:
1. Attempt to compile the C file that includes "conio.h" header.
2. Encounter compilation errors or warnings related to the "conio.h" header.

Expected Behavior:
The code should compile without any issues, and the functionality provided by the "conio.h" header should be available.

Actual Behavior:
The compilation fails, indicating that the "conio.h" header is either missing or incompatible.

Additional Information:
- gcc (GCC) 13.1.1 20230429
- fatal error: conio.h: No such file or directory
- Any relevant details about your development environment.

I would appreciate any guidance or assistance in resolving this issue. Thank you.

### PR DESCRIPTION
**Pull request by harshsoni-harsh**
# Title and Issue number 
Incompatibility Issue with 'conio.h' Header in C Program. https://github.com/pranjay-poddar/Dev-Geeks/issues/1961

Close #1961 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by harshsoni-harsh** [comment]
@MohitGupta121  check it out.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@harshsoni-harsh that's not an issue, you had to make changes in all files at once so I consider this type of PR a spam

**Comment by harshsoni-harsh** [comment]
but that's a simple issue, due to which code is not working.

**Comment by MohitGupta121** [comment]
Is you have any other  issue like this do it in one PR and avoid this type of contribution sorry we can't merge this.

**Pull request closed without merging**
