### PR TITLE
Website added

### LINKED ISSUE #2544: Wants to Add new E-commerce website
**Describe the project you want to add with tech stack**

Hi I want to add an e-commerce website
**Expected behavior**

**Screenshots (optional)**

e-commerce

**Additional context (optional )**

Also please add Gssoc23 label
Thank You

### PR DESCRIPTION
**Pull request by gulshanjakhon**
# Title and Issue number 

Close #2544

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by gulshanjakhon** [comment]
Hi @pranjay-poddar Please review and assign the gssoc23 label

Thank you

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@gulshanjakhon please remove the image from PR and upload it somewhere in cloud and use the link of the image to load the image into your Project.

**Comment by gulshanjakhon** [comment]
hi, @MohitGupta121 which image you are talking about?

> @gulshanjakhon please remove the image from PR and upload it somewhere in cloud and use the link of the image to load the image into your Project.

**Comment by MohitGupta121** [comment]
@gulshanjakhon all types of images, jpg, png, jifff, videos, everythings related to graphics

**Comment by gulshanjakhon** [comment]
> @gulshanjakhon all types of images, jpg, png, jifff, videos, everythings related to graphics

This will take lot of time

**Comment by MohitGupta121** [comment]
This will take only 30min, you just need to upload all images somewhere and paste the image link instead of path.

If not then we can close this PR.

**Comment by gulshanjakhon** [comment]
I will do it in 1-2 days, is it fine?

**Comment by MohitGupta121** [comment]
Take your time

**Pull request closed without merging**
