### PR TITLE
Issue 4534 Made the microsoft logo animation

### LINKED ISSUE #4534: microsoft logo animation
https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/9fa5e454-b2ad-4667-adce-b53518ee3ca1

### PR DESCRIPTION
**Pull request by abansal15**
#4534 

Close #4534 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
now there is only single project

**Comment by abansal15** [comment]
@MohitGupta121 i have made the required changes now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
