### PR TITLE
4558 added my black jack game

### LINKED ISSUE #4558: black jack game
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4558 

Close #4558 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
done

**Comment by abansal15** [comment]
@MohitGupta121 made the changes now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
