### PR TITLE
Heart Attack Risk Prediction (Deployed)

### PR DESCRIPTION
**Pull request by smty2018**
# Title and Issue number 
Heart Attack Risk Prediction ML Model (Deployed)
Frontend 

image
image

Backend(Decision Tree Classifier)

image

Close #<issue_no>

Closes issue #3835 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by smty2018** [comment]
@MohitGupta121 @TusharKesarwani

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Put your project inside Machine Learning folder

**Comment by smty2018** [comment]
@TusharKesarwani Done. Can you please re-review the pr. thank you

**Comment by smty2018** [comment]
@MohitGupta121 @TusharKesarwani can you please review and merge this PR. Thanking You in advance

**Review by MohitGupta121 — APPROVED** [review]

**Pull request closed without merging**
