### PR TITLE
4484 added the new animating button

### LINKED ISSUE #4484: New animating button
**Describe the Feature you want to end**

made this new button please see it and could you please assign it to me

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/32f099a8-b832-4299-8b11-133545f9b661

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4484 

Close #4484 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
helllo @TusharKesarwani , @MohitGupta121 please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
now there is only single project in this pr

**Comment by abansal15** [comment]
@MohitGupta121 made the changes now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
