### PR TITLE
Added the color changing animation

### LINKED ISSUE #4812: simple color changing box animation
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/10d92f28-1acf-45ce-8e1e-f7ab79378c1d

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4812 

Close #4812 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121  @TusharKesarwani added the animation please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121  @TusharKesarwani  please review it

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
