### PR TITLE
Enhanced Community page

### LINKED ISSUE #3349: Enhancing  Community Page
**Describe the Feature you want to end**
Would like to add action to the register button

**Expected behavior**
This way clients can regitser and explore to join the site

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by SnigdhaP2022**
# Styling elements and new components added to Community Page

Close #3349 

# Checklist:

- [✅] I have mentioned the issue number in my Pull Request.
- [✅] I have commented my code, particularly in hard-to-understand areas
- [✅] I have created a helpful and easy to understand `README.md`

Screenshot 2023-07-13 at 7 23 01 PM

Screenshot 2023-07-13 at 7 23 08 PM

### CODE REVIEW

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,review this please

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  Kindly, review this please

**Comment by SnigdhaP2022** [comment]
@TusharKesarwani  Kindly, review this please.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,look into this

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 kindly, review into this regarding level of the work

**Comment by SnigdhaP2022** [comment]
@TusharKesarwani Kindly,review this please

**Pull request merged**
