### PR TITLE
 Globe-Quest ( A front-end project) : A fully responsive Travel Website with Dark and Light Mode. 

### PR DESCRIPTION
**Pull request by Deepanshi177**
Globe-Quest: A fully responsive Travel Website with Dark and Light Mode.

Description:- Created a fully responsive tour and travel website that focused on travel reviews and trip fares. Used the toggle button to switch between dark and Light Mode to enhance readability. Adding the images of the website for reference.

Screenshot (38)

Screenshot (39)

### CODE REVIEW

**Comment by Harikaraja** [comment]
please assign me the issue

**Comment by pranjay-poddar** [comment]
Mention the issue number and strictly follow and fillup the PR template.

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
.

**Comment by MohitGupta121** [comment]
Inactive

**Pull request closed without merging**
