### PR TITLE
Sign Up page added

### LINKED ISSUE #1069: Add : Signup page for Apple E-commerce website [GSSOC'23]
I would like to add or create a sign up page with js validation for the Apple E-commerce website. 

Expected behavior
The primary purpose of a sign-up page is to capture user details and create a unique account for them within the system.

### PR DESCRIPTION
**Pull request by Pragati-3003**
I have added the signup page with data validation in the apple E-commerce website . I kindly request you to review these modifications and inform me if there are any other sections you would like me to address or make changes to.
issues #1069.
Closes #1069.
[x] I have mentioned the issue number in my Pull Request.
[x] I have commented my code, particularly in hard-to-understand areas
Thanking You.

### CODE REVIEW

**Comment by Saurabh-kumar09** [comment]
@Pragati-3003 Please add your issue number above. Then only I can review this PR.

**Comment by Pragati-3003** [comment]
> @Pragati-3003 Please add your issue number above. Then only I can review this PR.

okie ,I'll edit it

**Review by pranjay-poddar — COMMENTED** [review]
Resolve conflicts and strictly follow the PR template

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Follow the PR template rules

**Comment by Pragati-3003** [comment]
> Resolve conflicts and strictly follow the PR template

Solved all the merge conflicts ,please check.

**Comment by Pragati-3003** [comment]
> Follow the PR template rules

Okie .

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Pragati-3003 please also resolve the PR conflicts. Thanks!

**Comment by Pragati-3003** [comment]
> @Pragati-3003 please also resolve the PR conflicts. Thanks!

Resolved all the merge conflicts.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
@Pragati-3003 resolve conflicts

**Comment by Pragati-3003** [comment]
> @Pragati-3003 resolve conflicts

@MohitGupta121  I have resolved merge conflicts , please check.

**Comment by MohitGupta121** [comment]
@pranjay-poddar please approve this.

**Comment by Pragati-3003** [comment]
@pranjay-poddar , please review and merge this PR.

**Pull request closed without merging**
