### PR TITLE
Flutter project

### LINKED ISSUE #2686: Flutter Expense_Project
**Describe the project you want to add with tech stack**
The Expense Manager Application, using Provider to manage state.

A Flutter sample app that shows a state management approach using the Provider package and shared preferences for saving data in mobile.

Assign this issue to me under GSSOC'23

### PR DESCRIPTION
**Pull request by shraddha761**
# Title and Issue number 

Close #2686 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by shraddha761** [comment]
@TusharKesarwani please review

**Comment by shraddha761** [comment]
@TusharKesarwani please review

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add only one project in one PR

**Comment by shraddha761** [comment]
@TusharKesarwani it is only one project i

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
You had made changes in two folders
Make changes in one folder only in one PR

**Pull request closed without merging**
