### PR TITLE
Frontend Project "Netflix Clone" Improved Styling

### LINKED ISSUE #3709: Frontend Project "Netflix Clone" Improved Styling
**Describe the Feature you want to end**
Changing few styling properties of the website to improve its design.

**Expected behavior**
Improved design of the website.

**Screenshots (optional)**

Current Design
ip (23)

Expected Updated Design
ip (22)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project "Netflix Clone" Improved Styling
Close #3709 

# Output

**Before**
op (10)

**After**
op (9)

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
> @MohitGupta121 Kindly review this pull request.

@MohitGupta121

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
@MohitGupta121 @TusharKesarwani Kindly review this pull request. It has been open for 3 days.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
