### PR TITLE
Added Medical Encyclopedia Scraper

### LINKED ISSUE #3615: Medical Encyclopedia Scraper in Python
**Describe the project you want to add with tech stack**
I'd add a medical encyclopedia project in ```python projects``` which web-scrapes data from the mediline. The structure of the project is such that:
- There is a class having various end-user accissable functions. 
- The user can use these functions in order to get the relevant data from the medical encyclopedia.  

**Expected behavior**
>The user would use the accessable functions from the Encyclopedia class to get their desired data from the website. The data would include the medical terms, their definitions and related information, their formation genesis information, and so on.  

**Additional context (optional )**
This project can easily be used by other python projects who would want to have this feature by just importing the class.

### PR DESCRIPTION
**Pull request by jaivsh**
## Medical Encyclopedia Scraper

This web scraper is made from the Jsoup and requests libraries in python. It has 3 different functions which the users can implement with:

- **byletter():** It returns all the medical entries in the encyclopedia starting with a particular english letter.
- **scrapebyurl():** It returns the medical data including references, review dates, content, topic-head and so on based on a particular mediline's url.
- **query():** This function takes a query from the users and returns all the matching terms/responses from the encyclopedia matching the user's query. If there is no matching response, than it returns None

## Usage Guidelines
- First import the scraper class like so: ```from mediscraper import MediEncyclopedia```
- Create an instance of the class like so: ```ency = MediEncyclopedia()```
- Call relevant functions as required. Ex: ```ency.byletter('A)``` or ```ency.scrapebyurl(url)``` or ```ency.query('Heart attack')```
- After call, the functions gonna return the relevant results. 

Close #3615 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jaivsh** [comment]
Hi @pranjay-poddar @MohitGupta121 @TusharKesarwani

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jaivsh please resolves conflicts

**Comment by jaivsh** [comment]
@MohitGupta121 I've resolved conflicts.

**Comment by jaivsh** [comment]
@MohitGupta121 I've resolved the issues, can u please check

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
