### PR TITLE
Frontend Project "Project_Tracking_Intro_Component" Homepage Buttons Styling

### LINKED ISSUE #3667: Frontend Project "Project_Tracking_Intro_Component" Homepage Buttons Styling
**Describe the Feature you want to end**
Working on the styling of the homepage buttons to improve their design.

**Expected behavior**
Improved design of the buttons.

**Screenshots (optional)**

Current Design
ip (11)

Expected Updated Design
ip (9)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project "Project_Tracking_Intro_Component" Homepage Buttons Styling
Close #3667 

# Output

**Before**
op (28)

**After**
op (26)

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request so that I can work on other issues.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N please resolves conflicts

**Comment by iamRabia-N** [comment]
> @iamRabia-N please resolves conflicts

@MohitGupta121 Done with resolving conflicts. You can review now.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
