### PR TITLE
giveaway project added under Js projects

### LINKED ISSUE #2620: Giveaway Project under JS projects
**Describe the project you want to add with tech stack**
I would like to add a giveaway project  in which time will keep on going to a particular date in future which will be shown live, I will do this using plain javascript.

**Expected behavior**
Time will keep on going till the timeline which is set in future and when it reaches that date , the giveaway will end.

**Screenshots (optional)**
Screenshot 2023-06-23 230533

### PR DESCRIPTION
**Pull request by rahulrana701**
# Giveaway Project under JS projects #2620

Close #2620

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

Screenshot 2023-06-26 210711

### CODE REVIEW

**Comment by rahulrana701** [comment]
hi @MohitGupta121 can you please check the pr

**Comment by rahulrana701** [comment]
@MohitGupta121 can you please review the pr .

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@rahulrana701 please check the project is not properly added in the files changes.

**Comment by rahulrana701** [comment]
@MohitGupta121 done as suggested now everything may work fine..

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
No it's still there, I recommend you to close this PR and create new one

**Pull request closed without merging**
