### PR TITLE
real-time notification

### LINKED ISSUE #2186: Real-Time notification app
#Real-Time notification app
Tech-Stack
1) ReactJs
2) Socket io

**Expected behavior**
It can send instant notification to the folder of post.
It is real time TCP connection between client and server.

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by BhartiNagpure**
# RealTime-notification app 2186

Close #2186 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by BhartiNagpure** [comment]
@pranjay-poddar please check the pull request.

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Do not add more than one project in one PR

**Comment by BhartiNagpure** [comment]
> Do not add more than one project in one PR

can I remove one project from this request.

**Comment by TusharKesarwani** [comment]
> > Do not add more than one project in one PR
> 
> can I remove one project from this request.

Yes you can

**Comment by BhartiNagpure** [comment]
How

**Comment by BhartiNagpure** [comment]
how

**Comment by BhartiNagpure** [comment]
I am created another pull request for reastaurant website.

**Pull request closed without merging**
