### PR TITLE
[GSSoC'23] Wishing Model completed

### LINKED ISSUE #1731: [GSSoC'23] Wishing model
**Describe the project you want to add with tech stack**

Title - **Wishing Model**
Technology - **PYTHON**

**Expected behavior**

- This model will open directly in the terminal,
- This model ask the occasion of wishing,
- Play the song of that occasion in the background,
- Creating a different emojis to wish, etc.

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Title and Issue number 

Title - Wishing Model
Issue number - #1731 

Close #1731 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@pranjay-poddar @Saurabh-kumar09 Sirs, please review my pull request for a successful contribution under GSSoC'23
I have done with this python model. On adding the more songs on the `musics` directory will expand this bot model.
This will give the children a happiest gift, smile to the youngers, etc. due to wishing in our coding style 😎

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Avdhesh-Varshney please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos, mp3 files.
This increase the whole Dev-Greek project size.
Thanks!

**Comment by Avdhesh-Varshney** [comment]
@pranjay-poddar @Saurabh-kumar09 @MohitGupta121 Sir, I will mind it and never adding large files again.
Please again review my pull request and requested to merge it into the main branch for a successful contribution under GSSoC'23 program
Thanks

**Review by MohitGupta121 — APPROVED** [review]
@Avdhesh-Varshney Thanks, LGTM

**Comment by Avdhesh-Varshney** [comment]
@TusharKesarwani Sir, Could you tell me how this project comes under Plagiarism. Is open source not a platform to learn or just made for applying plagiarism ?

**Pull request merged**
