### PR TITLE
Added Chuck Norris Random Joke Generator

### LINKED ISSUE #4189: Chuck Norris random joke generator in Javascript
**Describe the project you want to add with tech stack**

I'd add a random joke generator written in javascript and html which would utilize the ```Chuck Norris API``` to generate random joke each time on button click.

**Expected behavior**

- User executes the application and clicks on "get joke" button.
- The joke appears on second screen. User can copy the joke through "copy" button.
- User can click on "New Joke" to get subsequent jokes.

### PR DESCRIPTION
**Pull request by jaivsh**
# Added the Random Joke generator project in Javascript 

I've implemented the Check Norris joke generator, which works with the help of the ```Chunk Norris``` API. 

Close #4189 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jaivsh** [comment]
@pranjay-poddar @MohitGupta121 @TusharKesarwani please assign me this!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jaivsh resolve conflicts

**Review by MohitGupta121 — COMMENTED** [review]
@jaivsh resolve conflicts

**Comment by jaivsh** [comment]
@MohitGupta121 conflicts resolved

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
