### PR TITLE
[GSSoC'23] Guess The Flag Game Completed

### LINKED ISSUE #2072: [GSSoC'23] Guess Country Flag Game
**Describe the project you want to add with tech stack**

Title - Guess the country flag
Tech - HTML, CSS and JS

**Expected behavior**

- Showing the image of the flag of different countries
- Adding a hint section, which tells the capital of that country
- If player tells the correct answer, score will increase by 1
- Otherwise decrease by 1, even if hint button is pressed

**Screenshots (optional)**

**Additional context (optional )**

This will enhance the knowledge of different countries by knowing the flags and capitals of the countries.
This site will boost the knowledge of children and they will learn from this site as adding many interesting facts in this website will enhance the attractiveness of this website.

### PR DESCRIPTION
**Pull request by Avdhesh-Varshney**
# Title and Issue number 

Title - Guess The Flag Game
Tech used - HTML, CSS and JS

Close #2072 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Avdhesh-Varshney** [comment]
@pranjay-poddar @Saurabh-kumar09 @MohitGupta121 Sirs, please review this pull request and requested to merge it into the main branch for a successful contribution under GSSoC'23 open-source program

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Avdhesh-Varshney please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your images, videos/images in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.
Thanks!

**Comment by Avdhesh-Varshney** [comment]
@MohitGupta121 Sir, now the folder size is **_686 KB_**. So, please review this pull request and requested to merge into the main branch.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Avdhesh-Varshney I not talking about folder size just remove images from this PR, and fetch or load images via link in your project.

**Comment by Avdhesh-Varshney** [comment]
@MohitGupta121 Sir Project completed. Please again review my pr.

Sorry sir for the disturbance.

**Pull request merged**
