### PR TITLE
Added Coyote and Chickens Javascript Game

### LINKED ISSUE #4753: Adding coyote and chickens javascript multiplayer game
**Describe the project you want to add with tech stack**

I'd add a javascript 2-d game in which there would be a coyote whose task is to catch all of his chickens, which are scattered around the 2-d space. He moves his position, and as a result of which, the chickens also move. His task is to move as and collect all of his chickens in minimum possible steps and create high scores. This is a multiplayer game in which one user plays as coyote and the other plays as chicken. The chickens also have the option to attack coyote and reduce his health. 

**Screenshots (optional)**

Screenshot 2023-08-05 at 9 50 25 AM

### PR DESCRIPTION
**Pull request by jaivsh**
# Added Coyote and chickens javascript game in Js-Games

I've aded the necessary game into the repository. This is a multi-player game in which one player plays as coyote and the other plays as chickens. The task is to remain survived till your enemy is knocked out. 

Close #4753 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jaivsh** [comment]
@pranjay-poddar @TusharKesarwani @MohitGupta121 please assign me this

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jaivsh remove this image or gif from PR and use it as a link after uploading somewhere else.

**Comment by jaivsh** [comment]
> @jaivsh remove this image or gif from PR and use it as a link after uploading somewhere else.

@MohitGupta121 done, please review now!

**Comment by jaivsh** [comment]
@MohitGupta121 please merge

**Comment by jaivsh** [comment]
@TusharKesarwani please

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
