### PR TITLE
Added Flutter Based Expense Tracker App

### LINKED ISSUE #3869: Add Flutter Based Expense Tracker App
**Describe the project you want to add with tech stack**

This app will allow users to enter their expenses, categorize them, and view reports on their spending habits.
It app will be built using the Flutter framework, which is a cross-platform framework that allows developers to build native-looking mobile apps for both iOS and Android.

**Expected behavior**

- The app allows users to track their expenses by entering details such as title, amount, and date.
- The app can be used to track expenses across different categories, such as food, transportation, and entertainment.
- The app is easy to use and can be customized to meet the needs of individual users.

### PR DESCRIPTION
**Pull request by tayyab-ilyas**
# Title and Issue number 

Close #3869 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by tayyab-ilyas** [comment]
hey @TusharKesarwani @MohitGupta121 ! can you guys have look at this? also please don't forget to add the Gssoc'23 label. Thanks!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@tayyab-ilyas please add only 1 project in 1 PR, there is currently 2 projects TO DO app, and Expense Tracker

**Comment by tayyab-ilyas** [comment]
> @tayyab-ilyas please add only 1 project in 1 PR, there is currently 2 projects TO DO app, and Expense Tracker

fixed it @MohitGupta121, thanks!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@tayyab-ilyas still same issue

**Comment by tayyab-ilyas** [comment]
I've created a new PR @MohitGupta121 please checkout #4044 , sorry for the trouble.

**Pull request closed without merging**
