### PR TITLE
added balloon splash games to js games (issue #120)

### PR DESCRIPTION
**Pull request by pranayjalan254**

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
mention issue number

**Comment by pranayjalan254** [comment]
mentioned (issue #435)

**Comment by pranayjalan254** [comment]
mentioned (issue #120)

**Comment by pranayjalan254** [comment]
kindly merge this pull request now Thank You

**Review by pranjay-poddar — COMMENTED** [review]
image

you have made a PR with three project in one make one PR for one Project, would recommend you to make a new PR

**Pull request merged**
