### PR TITLE
Added a Educational website

### PR DESCRIPTION
**Pull request by vedsom**
Bright Minds - Google Chrome 22-07-2022 18_21_16
Bright Minds - Google Chrome 22-07-2022 18_21_39
Bright Minds - Google Chrome 29-05-2022 22_02_11
Bright Minds - Google Chrome 22-07-2022 18_24_43

### CODE REVIEW

**Comment by vedsom** [comment]
@pranjay-poddar work is done, kindly review the PR. Thanks!!

**Review by pranjay-poddar — APPROVED** [review]

**Comment by pranjay-poddar** [comment]
@vedsom please mention the issue number in the following format:
 #227

**Comment by vedsom** [comment]
> @vedsom please mention the issue number in the following format: #227

Sorry didn't get it?

**Comment by pranjay-poddar** [comment]
Fill the PR template correctly and mention the issue number is #227

**Pull request merged**
