### PR TITLE
Social Media Reference Landing Page [GSSoC'23] #2085

### LINKED ISSUE #2085: Social Media Reference Landing Page Project [GSSoC'23]
### Description :
A social media reference landing page is a webpage that is specifically designed to showcase an individual's social media presence. It typically includes links to an individual's profiles on various social media platforms, as well as information about their content, and engagement.
Everything you are. In one, simple link in bio.
𝗧𝗲𝗰𝗵 𝗦𝘁𝗮𝗰𝗸 : HTML5, CSS3

**Screenshot :**

img

Hello @pranjay-poddar @MohitGupta121 @Saurabh-kumar09 ,
I'm interested in adding this project and would like to contribute. Could you please assign it to me under the GSSoC'23. I'm looking forward to collaborating on this project.
Thank you!

### PR DESCRIPTION
**Pull request by amankumar100**
Social Media Reference Landing Page [GSSoC'23] #2085

Close #2085

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
Screenshot (34)
Screenshot (35)

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Move files to java projects folder from root folder

**Comment by amankumar100** [comment]
Done, moved to Java Projects folder.

**Comment by amankumar100** [comment]
Please approve my pull request. It's been 2 days.

**Comment by MohitGupta121** [comment]
@pranjay-poddar please approve this PR.

**Pull request closed without merging**
