### PR TITLE
Add files via upload

### LINKED ISSUE #3529: Password Generator
**Describe the project you want to add with tech stack**
Password Generator

**Expected behavior**
It's a automatic password generator system according to your need.
**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Ijaiswalshivam**
Password Generator #3529

Close #3529 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Ijaiswalshivam** [comment]
directly uploaded the files as dev-geeks file size was too large when it was downloading.
now you can merge it. @TusharKesarwani

**Review by MohitGupta121 — COMMENTED** [review]
Already have project

**Comment by Ijaiswalshivam** [comment]
But it have some unique features

**Comment by MohitGupta121** [comment]
@Ijaiswalshivam if unique then apply that in existing project

**Comment by Ijaiswalshivam** [comment]
Ok..

**Pull request closed without merging**
