### PR TITLE
preloading

### LINKED ISSUE #3230: 3D preloading
**Describe the project you want to add with tech stack**

A 3D preloaders used to load the pages and websites creating effective view. 
**Expected behavior**

**Screenshots (optional)**

Screenshot 2023-07-08 093145

**Additional context (optional )**

kindly assign me under gssoc'23

### PR DESCRIPTION
**Pull request by Shreya111111**
# Title and Issue number 

Close #3230 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Shreya111111** [comment]
@MohitGupta121 plz review it under gssoc'23 issue  closes #3230 and PR #3322

**Comment by Shreya111111** [comment]
@MohitGupta121 kindly review the pr

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shreya111111 your project is Preloading then why are you uploading footers? I that part of your project?

**Comment by Shreya111111** [comment]
@MohitGupta121  it is different from footerui. preloaders are basically used before loading the website . It is used when page content are still loading. both are different projects.

**Comment by Shreya111111** [comment]
@MohitGupta121 is there any issue

**Comment by MohitGupta121** [comment]
@Shreya111111 there are 2 projects in your PR but you only have to upload the project that mentioned in your PR.

**Comment by Shreya111111** [comment]
@MohitGupta121 this is that one only

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shreya111111 Still there are two Projects :
1. Animated footer and Preloaders.
I request you to make new clean PR. I closing this for now.

**Pull request closed without merging**
