### PR TITLE
Added the Aim training Game

### LINKED ISSUE #3148: [GSSOC'23] Aim Training Game
## **Description 📃**
Aim training game is a simple and addictive game where the player's objective is to pop as many bubbles as possible within a limited time. Colorful bubbles randomly appear on the screen, and the player must quickly click on them to pop them. Each popped bubble earns the player a point, and the score is displayed in real-time. The game lasts for 30 seconds.

## **Expected behavior**
Colorful bubbles appear randomly on the screen at regular intervals.
The player can click on the bubbles to pop them and earn points.
The player's score is displayed in real-time, showing the number of bubbles popped.
The highest score achieved is tracked and displayed as the high score.

## **Screenshots (optional)**
Aim_Training

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by aditya-agr**
## Close #3148 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by aditya-agr** [comment]
@MohitGupta121 @pranjay-poddar please merge and approve this PR.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@aditya-agr resolve conflicts please

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@aditya-agr resolve conflicts

**Comment by aditya-agr** [comment]
@MohitGupta121 @pranjay-poddar please merge and approve this PR.

**Review by MohitGupta121 — COMMENTED** [review]
@aditya-agr please resolves conflicts

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
