### PR TITLE
[gssoc'23] - Custom Javascript Cursor Scroll //GSAP

### PR DESCRIPTION
**Pull request by animex007**
# GSAP/JAVASCRIPT - Custom Cursor Effect on Hover  #1774

# Description:
- this is custom javascript cursor
- anyone can use these for making their website look elegant!
- you can use this as a navbar or make it interactive with GSAP

# screenshot :
- when the cursor in hovering,
Screenshot 2023-06-10 214854

- when you move the cursor over the text,
Screenshot 2023-06-10 214922

- Example,

https://github.com/pranjay-poddar/Dev-Geeks/assets/93252366/21390b71-2d9e-4d3f-aef3-31e15ced9aae

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@animex007 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by animex007** [comment]
> @animex007 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

changes done ! added a screenshot and animated gif for better reference

**Comment by MohitGupta121** [comment]
@animex007 please resolve conflicts also.

**Comment by animex007** [comment]
> @animex007 please resolve conflicts also.

resolve the merge conflict, and also the done the changes!

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
