### PR TITLE
Group Connect (Web - Chat app)

### LINKED ISSUE #1785: Group-Connect
**Project Description**

This a chat application, which is a real-time messaging platform that allows users to communicate with each other in private or group chats. Users can create accounts, join existing chat rooms, send messages, and receive notifications when new messages arrive. The application aims to provide a seamless and interactive chat experience for users.

**Expected behavior**

The chat application should properly handle special characters and display them correctly in the chat room. Emojis and symbols should be rendered as intended without causing any layout issues.

**Screenshots (optional)**
If applicable, I will provide screenshots to showcase the progress and highlight significant aspects during its development.

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by U-DAY-333**
# Title and Issue number 

Adding Group Connect (Web Chat application) using Node Js
Close  #1785 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Follow the PR template properly

**Comment by U-DAY-333** [comment]
I have made the changes sir. Please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@U-DAY-333 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by U-DAY-333** [comment]
Sure sir , But the Change is Typo in PR and i have corrected it. Please review it sir

**Comment by MohitGupta121** [comment]
@U-DAY-333 anything to be a better review it's good to have a proof.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@U-DAY-333 also please follow PR template that we have in default. Thanks!

**Comment by U-DAY-333** [comment]
I have made the changes sir, Please review it

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — APPROVED** [review]

**Pull request closed without merging**
