### PR TITLE
Flappy dragon (python game ) issue #4060 

### LINKED ISSUE #4060: Flappy Dragon Python Game
**Describe the project you want to add with tech stack**
I want to add a python project name Flappy Dragon .

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Adityamishra9719**
# Title and Issue number 
Flappy Dragon Python Game 
issue #4060 

Close #4060 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Make changes in one project in one PR

**Comment by Adityamishra9719** [comment]
> Make changes in one project in one PR

can you pls tell what changes i have to do i'm not able to understand

**Comment by TusharKesarwani** [comment]
> > Make changes in one project in one PR
> 
> can you pls tell what changes i have to do i'm not able to understand

You should add only one project in one PR

**Comment by Adityamishra9719** [comment]
okk

**Pull request closed without merging**
