### PR TITLE
4483 Added the download button

### LINKED ISSUE #4483: Downloading animation
**Describe the Feature you want to end**

i have made this downloading annimation could you please assign it to me

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/8d095fa6-f095-454d-aff6-ecbe517b20ac

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4483 

Close #4483 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121 , @TusharKesarwani  please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
done

**Comment by abansal15** [comment]
@MohitGupta121 made the required changes now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
