### PR TITLE
Added Heritage Institute of Technology landing page

### LINKED ISSUE #2667: Website for Heritage Institute of Technology Kolkata
**Describe the project you want to add with tech stack**
A Website for Heritage Institute of Technology Kolkata
Using HTML CSS and Javascript
Responsive, functional website

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
# Title and Issue number 
Website for Heritage Institute of Technology Kolkata #2667

Close #2667 
# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/34159eda-dd6e-417d-9386-da9d74c06397

### CODE REVIEW

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121 Please merge this PR

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121

**Comment by PoulavBhowmick03** [comment]
@pranjay-poddar @MohitGupta121

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121 Please merge this

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
