### PR TITLE
[ADDED]: Flutter Instagram Clone

### LINKED ISSUE #2771: [ADD]: Instagram Flutter Clone
**Describe the project you want to add with tech stack**

A completely Responsive Instagram App- Works on Android, iOS & Web!

Tech Stack:
- Flutter

**Expected behavior**

A clone of Instagram.

### PR DESCRIPTION
**Pull request by Killer2OP**
# Title and Issue number 

Flutter Responsive Instagram Clone 

Close #2771 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Killer2OP** [comment]
@pranjay-poddar @MohitGupta121 @TusharKesarwani Can you please review my PR :)

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Killer2OP please resolve conflicts

**Comment by Killer2OP** [comment]
> @Killer2OP please resolve conflicts

Done 👍

**Review by MohitGupta121 — APPROVED** [review]

**Comment by killingkillers** [comment]
Hello @MohitGupta121 & 
I think he is copied the code from :-  https://github.com/Abhisheksolanki19/Flutter-Instagram-clone-App
Please check the code, even the variables are same. I don't think is a coincidence please remove the labels.

### Proof : 
Screenshot from 2023-07-03 01-25-34


Screenshot from 2023-07-03 01-25-27


Check the index.html code even the comments lines are same. It's really unfair for the real contributors.

**Comment by 0xabdulkhalid** [comment]
Hey there @killingkillers, you got my respect 💯

**Comment by 0xabdulkhalid** [comment]
The sickest part is the dude just copying the whole repository content even license, .gitignore, issue & pr-templates.

I don't know who are you @killingkillers, but don't fear to give the collected proofs to take the right action.
We can inform to the GSSOC Team regarding this by raising a ticket.

**Comment by killingkillers** [comment]
Hey @0xabdulkhalid ,
I'm here to kill the fools.
The files are absolutely same I request admin to remove the labels. 
@0xabdulkhalid You can also contact the GSSoC 23 official and @gurjeetsinghvirdee about this.

**Comment by shraddha761** [comment]
@killingkillers I request you to check @0xabdulkhalid pr also he also added lots of project in dev geeks. I don't think so he created by himself

**Comment by killingkillers** [comment]
@shraddha761  Okay don't worry I'm going to end this scam soon.

**Comment by 0xabdulkhalid** [comment]
Hey @shraddha761, you can verify my pr's.

Every project are add by me are done by me, they are all Frontend mentor projects.
And the recent javascript projects are also from my 30-days-of-Javascript-Challenge.

**Comment by killingkillers** [comment]
> Hey @shraddha761, you can verify my pr's.
> 
> Every project are add by me are done by me, they are all Frontend mentor projects. And the recent javascript projects are also from my 30-days-of-Javascript-Challenge.

Okay, don't worry I can detect who is scammer or not.
If you are not copying then don't worry.

**Comment by killingkillers** [comment]
@gurjeetsinghvirdee .... check this too.

**Comment by 0xabdulkhalid** [comment]
Yeah @killingkillers, that's what i'm saying to @shraddha761.

I don't want to worry, because the ones who copied want to worry.

I can easily map to original source code on my profile with proof.

**Pull request merged**
