### PR TITLE
Tic Tac Toe project using javascript

### LINKED ISSUE #1236: Add a Tic Tac Toe project using javascript
I want to add a Tic Tac Toe game using html css and javascript as a project. It will also help other fellow contributors to contribute in the new project.

### PR DESCRIPTION
**Pull request by AyishikD**
Tic Tac Toe project using javascript
Issue number #1236 

Close #1236 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by AyishikD** [comment]
I have also added option to play against AI

**Comment by AyishikD** [comment]
@pranjay-poddar Please can you review my work

**Comment by AyishikD** [comment]
@pranjay-poddar Please can you review my work and merge it

**Comment by AyishikD** [comment]
@Saurabh-kumar09 Please can you check this and merge

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@AyishikD please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by AyishikD** [comment]
> @AyishikD please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

Yeah sure I am adding it

**Comment by AyishikD** [comment]
@MohitGupta121 I have added the screenshots in the PR

**Review by MohitGupta121 — APPROVED** [review]
@AyishikD LGTM, Thanks.

**Pull request merged**
