### PR TITLE
Add gadget ecommerce

### LINKED ISSUE #2415: Add gadged ecommerce landing page
**Describe the project you want to add with tech stack**
This is a 5 pages E-Commerce website built with HTML, CSS, and Bootstrap. The website is static, and buttons and links isn't working. My biggest project so far using HTML CSS and BOOTSTRAP.

**Expected behavior**

**Screenshots (optional)**
image
image

**Additional context (optional )**
Pls assign this to me under gssoc23

### PR DESCRIPTION
**Pull request by jfmartinz**
# #2415 Add gadget ecommerce landing page

Close #2415 

Can someone add a level and a gssoc label on it? Thank you!!
image
image

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jfmartinz** [comment]
@MohitGupta121 can you check?

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jfmartinz please not upload images in your PR use the required images as from link in your index.html. for example you can upload somewhere your images and load them via link in your project.

**Comment by jfmartinz** [comment]
> @jfmartinz please not upload images in your PR use the required images as from link in your index.html. for example you can upload somewhere your images and load them via link in your project.

so i will remove the img folder and instead just replace the link?

**Comment by jfmartinz** [comment]
> > @jfmartinz please not upload images in your PR use the required images as from link in your index.html. for example you can upload somewhere your images and load them via link in your project.
> 
> so i will remove the img folder and instead just replace the link of each images?

**Comment by MohitGupta121** [comment]
@jfmartinz remove whole image folder and wherever you using that images use the cloud link for that images ( drive or github or any cloud)

**Comment by jfmartinz** [comment]
@MohitGupta121  pls check thank yyou!!

**Comment by jfmartinz** [comment]
> @MohitGupta121 pls check. thank you!

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
