### PR TITLE
Added Pokemon App [GSSOC'23]

### LINKED ISSUE #4547: Pokemon App
**Describe the project you want to add with tech stack**
To  Add a Pokemon App made using ReactJs and using PokeAPI.

**Expected behavior**
Will give information of pokemon which the user want to see.

### PR DESCRIPTION
**Pull request by Ayushkumargit7**
# Title and Issue number 
Pokemon App

Issue #4547 
Close #4547 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 @pranjay-poddar @TusharKesarwani 
Please review and merge the PR.
And add the gssoc23 label and level label.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
Make PR before assign

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 
Sometimes you take more than 2 days or greater , to assign a issue , so because of that i already made a PR.
Please remove the spam and invalid label , and add level label.

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 
Please add the level label.

**Pull request merged**
