### PR TITLE
Dice game using html, CSS and JavaScript #524

### PR DESCRIPTION
**Pull request by ayushkedia05**
# Title and Issue number 

Dice game using html, CSS and JavaScript #524

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by ayushkedia05** [comment]
Can you please tell what mistake I have done as there is already a issue about doubt game and I pointed to it.

I also made a classroom dashboard as should I raise issue for that??

**Comment by pranjay-poddar** [comment]
> Can you please tell what mistake I have done as there is already a issue about doubt game and I pointed to it.
> 
> I also made a classroom dashboard as should I raise issue for that??

Yes

**Comment by pranjay-poddar** [comment]
While raising PR follow the template and fill the checklista else PRs will be rejected automatically.

**Comment by ayushkedia05** [comment]
can you please provide hacktober accepted label.

**Pull request merged**
