### PR TITLE
sentiment analysis tweets of Twitter 

### LINKED ISSUE #2759: sentiment analysis tweets of twitter [MACHINE LEARNING ]PYTHON
**Describe the project you want to add with tech stack**
this project is about to analysis of the tweet of the tweeter. 

**Expected behavior**
in a data set of 30k around i'm going to develop the LOGSITIC REGRESSION model the fits on the data set which i'm using with the accuracy of 90-95%.
for easy to understand i will use lib of MATPLOT lib for represent and analysis of the data.
**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/2379ce79-1f6f-4590-a357-f329bfeaa503

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Sushilverma002**
# Title and Issue number 
issue no #2759 

Close #2759 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/7342a578-d0cc-448b-bcb8-306592010f39

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@pranjay-poddar please merge it

**Comment by Sushilverma002** [comment]
@pranjay-poddar please review and merge it

**Comment by Sushilverma002** [comment]
@pranjay-poddar please merge it

**Comment by Sushilverma002** [comment]
@pranjay-poddar please review and merge

**Comment by Sushilverma002** [comment]
@pranjay-poddar please review

**Comment by Sushilverma002** [comment]
@pranjay-poddar please merge this pr

**Comment by Sushilverma002** [comment]
@pranjay-poddar please merge this pr

**Comment by Sushilverma002** [comment]
@pranjay-poddar please merge this pr

**Comment by Sushilverma002** [comment]
@MohitGupta121 video is added for review fast have a look

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
