### PR TITLE
New Frontend Project Added 

### LINKED ISSUE #4726: Frontend Project To-do List Generator and Manager Responsive Website
**Describe the project you want to add with tech stack**
To-do list generator and manager website.
It is made with tech stack of HTML, CSS, JavaScript and JQuery.

**Expected behavior**
Attractive designed website.

**Additional context (optional )**
No

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project To-do List Generator and Manager Responsive Website

Close #4726

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
Hi @MohitGupta121 
The new project is added which is made with tech stack of HTML, CSS, JavaScript and JQuery.

**Comment by iamRabia-N** [comment]
Kindly review this pull request.

**Comment by iamRabia-N** [comment]
Hi @MohitGupta121
Kindly review this pull request.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by iamRabia-N** [comment]
@MohitGupta121 In this pull request, project is added. And 'level2' assigns to addition of project

**Comment by iamRabia-N** [comment]
> @MohitGupta121 In this pull request, project is added. And 'level2' assigns to addition of project

@TusharKesarwani

**Comment by iamRabia-N** [comment]
> @MohitGupta121 In this pull request, project is added. And 'level2' assigns to addition of project

@TusharKesarwani Add correct level

**Pull request merged**
