### PR TITLE
[GSSoC'23]PR for issue #3050 

### LINKED ISSUE #3050: Send Emails Using SMTP in Python
**Describe the project you want to add with tech stack**
To send email following libraries and modules are used :
   * smtplib
   * EmailMessage
   * starttls
   
**Expected behavior**
Python provides smtplib module, which defines an SMTP client session object that is used to send the emails.

**Screenshots (optional)**

IMG-20230705-WA0008

**Additional context (optional )**
SMTP provides easy way to send mail from one server to another.

### PR DESCRIPTION
**Pull request by ahana02**
# SMTP mailing #3050 

Close #3050 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by ahana02** [comment]
@MohitGupta121 @pranjay-poddar please review the PR, add GSSoC labels, and merge it.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@ahana02 please resolve conflicts

**Review by ahana02 — COMMENTED** [review]
Resolved the conflict

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@ahana02 please resolves conflicts

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
