### PR TITLE
Added the footer to the website.

### LINKED ISSUE #1779: Designing and creating a footer with Figma + coding [GSSoC'23]
**Describe the Feature you want to end**
The homepage of the website doesn't have a footer. I can design and create a footer for the website.

**Expected behavior**
To have a footer

**Screenshots (optional)**
Here are some sample footer I designed in Figma;
footerprafter
FOOTER@
FOOTER

**Additional context (optional )**
Please assign me this issue under GSSoC'23

### PR DESCRIPTION
**Pull request by 1Shubham7**
after footer
# Title and Issue number 
Added the footer to the website. 
Closes #1779 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

Before :
before footer

After :
after footer

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Remove branch conflicts

**Comment by 1Shubham7** [comment]
I don't have the permission

**Comment by pranjay-poddar** [comment]
You don't need any permission to resolve conflicts

**Comment by 1Shubham7** [comment]
The option to resolve conflicts was not on,

**Pull request closed without merging**
