### PR TITLE
Added Fully Responsive University Website [GSSOC'23]

### LINKED ISSUE #2487: University Website Fully Responsive
**Describe the project you want to add with tech stack**
A Fully Responsive University Website made using HTML and CSS .It has 5 pages HOME , ABOUT , COURSE , BLOG  and CONTACT. 

**Expected behavior**
Person can get the full overview of the college through the website.

**Screenshots (optional)**
image
image
image
image
image
image
image
image

**Additional context (optional )**
Made with fun and learnings .

### PR DESCRIPTION
**Pull request by Ayushkumargit7**
# Title and Issue number 
Fully Responsive University Website

Issue #2487
Close #2487

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 @pranjay-poddar @TusharKesarwani 
Please review and merge the PR.
And add the gssoc23 label and level label.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Ayushkumargit7 please remove all images from the PR and upload them somewhere in the cloud then use them in your Project through the link.

**Comment by Ayushkumargit7** [comment]
I pushed the changes but it gives the below error i think @MohitGupta121  you merged the changes that's why i think.The errors are below -  
! [rejected]          uni -> uni (fetch first)
error: failed to push some refs to 'https://github.com/Ayushkumargit7/Dev-Geeks.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Ayushkumargit7** [comment]
@pranjay-poddar @TusharKesarwani @MohitGupta121 Please see above message and merge the pr.

**Comment by Ayushkumargit7** [comment]
There was issue here as told above , i resolved it , by commit again from start, i opened another pr , i am closing this one.

**Pull request closed without merging**
