### PR TITLE
Product Preview Component

### LINKED ISSUE #1955: Product Preview Card Component
**Describe the project you want to add with tech stack**

Product Preview Card using HTML and CSS in Frontend-Projects 

## Issue Type:
- [x] New Project

**Screenshots**
d0bm3lh8bp36gyi3jiop

### PR DESCRIPTION
**Pull request by MisterMickey**
# Product Preview Component 

Close #1955 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

d0bm3lh8bp36gyi3jiop

### CODE REVIEW

**Review by pranjay-poddar — APPROVED** [review]

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Remove branch conflicts

**Comment by MisterMickey** [comment]
@pranjay-poddar Done.

**Comment by pranjay-poddar** [comment]
Check again

**Comment by MisterMickey** [comment]
@pranjay-poddar Done again.

**Review by pranjay-poddar — APPROVED** [review]

**Pull request merged**
