### PR TITLE
Added Mapty project

### LINKED ISSUE #1872: Mappy- a geological website helping in marking the location and your workout
**Describe the project you want to add with tech stack**
A website made using HTML, CSS and advanced Javascript which uses OpenStreetMap API to show user the map of their location, they can mark the place they want and choose the workout they want, distance they would cover, workout timing and other stuffs

**Screenshots (optional)**

image

image

### PR DESCRIPTION
**Pull request by PoulavBhowmick03**
# Title and Issue number 
Mapty
Issue #1872 

Close #1872 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@PoulavBhowmick03 can you please add screen recording of your project so that it make easy for reviewers.
Thanks!

**Comment by PoulavBhowmick03** [comment]
Sure @MohitGupta121 
Here it is

https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/a153693c-2551-4e5c-a84e-c85774ebab1d

**Comment by PoulavBhowmick03** [comment]
@MohitGupta121 Can you please check it and merge it so that I can create the PRs for other issues?

**Review by MohitGupta121 — APPROVED** [review]
@PoulavBhowmick03 Thanks, LGTM

**Comment by MohitGupta121** [comment]
@pranjay-poddar PTAL, make a review pass from your side from merge this. 
Thanks.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@PoulavBhowmick03 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by PoulavBhowmick03** [comment]
I have already added, and you checked that.. right?
Here is the recording

https://github.com/pranjay-poddar/Dev-Geeks/assets/133862694/a153693c-2551-4e5c-a84e-c85774ebab1d

**Review by MohitGupta121 — APPROVED** [review]
@PoulavBhowmick03 LGTM, Thanks

**Pull request merged**
