### PR TITLE
ADD Emi calculator

### LINKED ISSUE #996: Add EMI Calculator Project
**Describe the project you want to add with tech stack**

I want to add an EMI Calculator project 
it will take the loan amount, interest rate, and loan tenure in a month

**Expected behavior**

It will calculate your EMI
EMI-calulator
 per month
**Screenshots (optional)**

**Additional context (optional )**

TECH STACK: html css javascript

### PR DESCRIPTION
**Pull request by Gurnav224**
# Add EMI Calculator Project #996

Close #996 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — COMMENTED** [review]
Please fill the pr template correctly with the #issue number and other details .

**Comment by Saurabh-kumar09** [comment]
@Gurnav224 Make the required changes. Mention your issue number. Then only I can review your PR.

**Comment by Gurnav224** [comment]
Hey I fill the pr template can you review  it

**Review by Saurabh-kumar09 — APPROVED** [review]

**Review by Saurabh-kumar09 — APPROVED** [review]

**Comment by Saurabh-kumar09** [comment]
@pranjay-poddar Please check this PR once.

**Review by MohitGupta121 — COMMENTED** [review]
@Saurabh-kumar09 I think we already have the [EMI Calculator ](https://github.com/pranjay-poddar/Dev-Geeks/tree/main/ML%20Projects/EMI%20CALCULATOR) project. So we can close this PR.

**Comment by Saurabh-kumar09** [comment]
@MohitGupta121 Yes, It's repeated. But I think we can keep this as it is Javascript project and previous was Python project. Otherwise it's also fine, if we close it.

**Comment by MohitGupta121** [comment]
@Saurabh-kumar09 Okay Thanks, whatever @pranjay-poddar suggests we go with that.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
Inactive

**Pull request closed without merging**
