### PR TITLE
feat: Added Razor pay Clone in Frontend Project. 

### LINKED ISSUE #3019: Add Razor pay Clone Created with HTML and Tailwind ✔
Description:
As a contributor, I would like to propose adding a Razorpay clone to the project. This clone will be developed using HTML and Tailwind CSS, allowing users to understand the functionality and UI/UX design.

image

### PR DESCRIPTION
**Pull request by Nishitbaria**
# Title and Issue number 

Add Razor pay Clone Created with HTML and Tailwind ✔

Close #3019 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Nishitbaria** [comment]
Hey @MohitGupta121  Please Review my Pr :)

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Nishitbaria  please remove all the images or gif from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

**Comment by Nishitbaria** [comment]
@MohitGupta121 I will Update it

**Comment by Nishitbaria** [comment]
Hey @MohitGupta121  I have Updated My File Please Review It

**Comment by Nishitbaria** [comment]
@MohitGupta121 Updated Please check my PR

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
