### PR TITLE
Added OTP verification system in python

### LINKED ISSUE #4260: OTP verification system project in Python
**Describe the project you want to add with tech stack**

I'd add an OTP verification system made in python which would firstly prompt user to sign in using gmail and then would send an OTP to their mail account. It would then prompt the user to type in the otp in the CLI. This way, the verification would be checked. 

**Expected behavior**

- User executed the program.
- User is prompted to login in their mail in the browser.
- When login is completed, the script would send an auto-OTP to their mail.
- The user would then have to type in the correct OTP to get verified.

### PR DESCRIPTION
**Pull request by jaivsh**
# Added OTP verification using SMTP in python 

I've completed the addition of OTP verification system in python. This program uses the functional decomposition to send the otp to a person's email id. 

Close #4260 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jaivsh** [comment]
@pranjay-poddar @MohitGupta121 @TusharKesarwani plase reiew this PR

**Review by TusharKesarwani — APPROVED** [review]

**Comment by TusharKesarwani** [comment]
Resolve Conflicts

**Comment by jaivsh** [comment]
> Resolve Conflicts

@TusharKesarwani done!

**Comment by jaivsh** [comment]
@TusharKesarwani I've resolved the conflict. Please do the needful

**Comment by MohitGupta121** [comment]
@jaivsh resolve conflicts

**Comment by jaivsh** [comment]
@MohitGupta121 please review this too, it's been too long since it is opened

**Comment by jaivsh** [comment]
@TusharKesarwani please check

**Pull request merged**
