### PR TITLE
Cat game using javascript

### PR DESCRIPTION
**Pull request by Kalivarapubindusree**
# Title and Issue number 

#2644 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Kalivarapubindusree** [comment]
@TusharKesarwani Please review this at once!

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add only one project in one PR

**Comment by Kalivarapubindusree** [comment]
Can you please review  this pr now  I removed another pr ,now it has only one pr now please check it out @TusharKesarwani

**Comment by Kalivarapubindusree** [comment]
Please checkout at once! @TusharKesarwani

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
