### PR TITLE
4474 Added my rock paper scissor game

### LINKED ISSUE #4474: new game rock paper scissor
**Describe the Feature you want to end**

**Expected behavior**

**Screenshots (optional)**

image

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4474 

Close #4474 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121 , @TusharKesarwani please review it

**Comment by abansal15** [comment]
image

**Comment by abansal15** [comment]
@MohitGupta121 , @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
done

**Comment by abansal15** [comment]
@MohitGupta121 done the changes now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
