### PR TITLE
updated typing speed test

### LINKED ISSUE #4263: improve the Typing_speed_test
**Describe the Feature you want to end**
improving typing speed test 
**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/1ae7f123-8ab6-4a52-90f9-a7b3aa0b463d

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by Sushilverma002**
# Title and Issue number 

Close #4263 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/114687502/89adcd81-f40e-4eca-b3ff-fba39ad0f75e

@MohitGupta121 please merge it.

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@MohitGupta121 @pranjay-poddar please merge it sir

**Comment by Sushilverma002** [comment]
@MohitGupta121 @pranjay-poddar have a look

**Comment by Sushilverma002** [comment]
@MohitGupta121 have a look

**Comment by Sushilverma002** [comment]
@MohitGupta121 please merge it

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
