### PR TITLE
Temperature Scale Changer #1997

### PR DESCRIPTION
**Pull request by amankumar100**
# Temperature Scale Changer #1997 

Close #<1997>

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

Screenshot (33)

### CODE REVIEW

**Comment by amankumar100** [comment]
Please approve my contribution. I have made this code successfully.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@amankumar100 Please follow these things in your PR:
1. Make sure you use PR template and add proper issue number linked in with "close" PR number as shown in example of PR template.
2. Please move all the file that you have added - Clones, Password Generator, Temp scale in there respective project folder as mention in [repo](https://github.com/pranjay-poddar/Dev-Geeks/pull/2005).

Thanks!

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 please do not merge this PR, the issue was opened by me and assigned to me too, but he has created the PR for the same issue and even mentioned my issue in his PR template.

**Comment by MohitGupta121** [comment]
@SoarinSkySagar Thanks man for updating, so this PR is consider to be spam.

**Pull request closed without merging**
