### PR TITLE
Frontend Project "netflix-clone" Navbar Position Correction 

### LINKED ISSUE #3710: Frontend Project "netflix-clone" Navbar Position Correction
**Describe the Feature you want to end**
Changing few styling properties of the navbar to improve its alignment.

**Expected behavior**
Improved position of the navbar.

**Screenshots (optional)**

Current Design
ip (20)

Expected Updated Design
ip (21)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project "netflix-clone" Navbar Position Correction 
Close #3710

# Output

**Before**
op (11)

**After**
op (12)

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
> @MohitGupta121 Kindly review this pull request.

@MohitGupta121

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
@MohitGupta121 @TusharKesarwani Kindly review this pull request. It has been open for 3 days.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
