### PR TITLE
Adding a front-end project: RouteEase [gssoc'23]

### LINKED ISSUE #1703: Adding a front-end project: RouteEase [gssoc'23]
**Describe the project you want to add with tech stack**
I want to add a front-end project which consists of multiple web pages, name of that project is RouteEase which is aimed to streamline the bus booking system for students and the Admin(in charge) of the Bus department. 
Tech Stack: HTML, CSS, JAVASCRIPT, JQUERY. 

**Screenshots (optional)**
Screenshot (203)
Screenshot (204)
Screenshot (205)
Screenshot (206)

**Additional context (optional )**
I am a GSSoC'23 contributor, please add the tag of gssoc'23 after assigning the task to me.

### PR DESCRIPTION
**Pull request by thevirengarg**
# Title and Issue number 
Front- end Project: RouteEase [gssoc'23]
Please add the tag of gssoc'23.

Close #1703 

https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/8660e462-e2e7-4f8d-bb09-50d2879b0891

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by thevirengarg** [comment]
@MohitGupta121 @pranjay-poddar please review this PR

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@thevirengarg please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by thevirengarg** [comment]
@MohitGupta121 I have added screen recording of the project, please review it. [gssoc'23]

**Review by MohitGupta121 — APPROVED** [review]

**Comment by thevirengarg** [comment]
@MohitGupta121 Can you please tell me, why you gave a level 1 tag to this PR as in onboarding call we were told that level 1 is given to minor bug fixes and documentation update, and level 2 is given for updating a feature, and level 3 is for adding a new feature, and this PR added a feature to the repo of DevGeeks.

**Pull request merged**
