### PR TITLE
Added the Alien Shooting Game

### LINKED ISSUE #3149: [GSSOC'23] Alien Shooting
## **Description 📃** 
- A retro styled game testing your reflexes and precision on the keyboard. Your main aim is to shoot as many aliens as you can using the shooter given to you.

## **Expected behavior**
- Easy to play
- Scoring system so that you can compare points with your friends.
- Responsive design for most of the monitors.

## **Screenshots (optional)**
Alien_Shooter

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by aditya-agr**
## Close #3149 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by aditya-agr** [comment]
@MohitGupta121 please merge and approve this PR.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@aditya-agr please resolve conflicts

**Comment by aditya-agr** [comment]
@MohitGupta121 The interface of both the shooting game is different so it is not a plagarized work. This is my version of UI for this game.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@aditya-agr resolves conflicts

**Comment by aditya-agr** [comment]
@MohitGupta121 please merge and approve this PR.

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
@Killer2-O Thanks.

**Comment by aditya-agr** [comment]
@MohitGupta121 The interface of both the shooting game is different so it is not a plagarized work. This is my version of UI for this game.
You can check in the issue. 
Please  remove this plagarism label.

**Comment by aditya-agr** [comment]
@Killer2-O  you can check screen shot from my issue #3149  both are different games.

**Comment by aditya-agr** [comment]
And please make remove this label of plagarism

**Pull request merged**
