### PR TITLE
done plz check

### PR DESCRIPTION
**Pull request by Swastik200**
done plz check

 folkdances #962 
Please make sure issue number is mention in Pull Request 

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Swastik200 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Swastik200** [comment]
Ok, will do that.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Swastik200 Also Please move your whole project to their respective project folder as mention in [repo](https://github.com/pranjay-poddar/Dev-Geeks/pull/2005).

**Comment by Swastik200** [comment]
Exams going on....Will do this after

**Pull request closed without merging**
