### PR TITLE
Added the food detector script

### PR DESCRIPTION
**Pull request by karthikbhandary2**
# Title and Issue number 

Food detector using PyTorch #2618 

Close #<2618>

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Put your project inside the respective folder

**Comment by karthikbhandary2** [comment]
which folder should I put it in? Should I put it in ML Projects?

**Comment by TusharKesarwani** [comment]
> which folder should I put it in? Should I put it in ML Projects?

You should put your project inside the respective folder according to your project tech stack

**Comment by karthikbhandary2** [comment]
Hey, I made the changes as mentioned. Please check @TusharKesarwani

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
