### PR TITLE
Modified: README.md

### PR DESCRIPTION
**Pull request by Emetegift**
# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Emetegift** [comment]
**Issue #1213 fixed**

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Resolve conflicts

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Emetegift are you still working on this PR, then please resolve conflicts. Thanks!

**Comment by MohitGupta121** [comment]
Inactive

**Pull request closed without merging**
