### PR TITLE
Instagram clone

### LINKED ISSUE #2179: Instagram_Clone
**Describe the project you want to add with tech stack**
This is a clone of our most popular social media platform Instagram

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by apu52**
# Title and Issue number 
I have successfully added Instagram Clone with Issue no. #2179 

Close #2179 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@apu52  please remove all the images from your PR and use them through cloud link. Upload somewhere the images and use them from that link.

**Comment by apu52** [comment]
ok Sir, I will Do that

**Comment by apu52** [comment]
Sir the images are directly used in clone so that I can't remove them. Please review my PR & please merge it.

**Comment by MohitGupta121** [comment]
@apu52 I not asking to remove images from project I'm saying you have to upload images somewhere else and use the image link instead of direct image path.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@apu52 Remove all images from the PR and upload them somewhere and instead of the image path use the exact image URL that you got after uploading the image.

**Comment by apu52** [comment]
Sir, I have removed the img file & previously also have added exact image url in HTML. Sir please merge the PR.

**Comment by apu52** [comment]
@MohitGupta121 Sir Plaease

**Review by MohitGupta121 — APPROVED** [review]

**Comment by apu52** [comment]
Thank you sir

**Pull request merged**
