### PR TITLE
[GSSOC'23] YouTube clone #1490

### PR DESCRIPTION
**Pull request by Enhancer18**
# Title and Issue number 

[GSSOC'23] YouTube clone #1490

Close #<1490>

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Enhancer18** [comment]
@Saurabh-kumar09 finished the PR plz review

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Enhancer18 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Enhancer18** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/assets/102911149/6eb2fe6e-1067-4873-9e7f-aa9b1f60733f

**Review by MohitGupta121 — APPROVED** [review]
@Enhancer18 Thanks, LGTM

**Pull request merged**
