### PR TITLE
feat: live repository statistics fetch for dev-geeks webpage 🚀✨

### LINKED ISSUE #3723: NEW FEATURE: FETCH DYNAMIC DATA FOR DEV-GEEKS REPO WITH API  🚀
## Description
- My idea is to make the count section of Dev-Geeks Repository website to dynamically fetch latest data of closed issues, closed prs, and contributors count.
- Currently they are all static values so that it can't update automatically we the developers need to automate it using Github Api to fetch latest data. 
- I can make this by adding the new feature with Github API to dynamically fetch this repository's data to display on the site.

## Screenshots ( Current behaviour )

https://user-images.githubusercontent.com/92252895/253804791-d7318daf-4861-429a-bafe-e0904a30a276.mp4

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
# Close #3723 

# Screenshots
|||
|:----:|:---:|
| **BEFORE** | Screenshot 2023-07-27 at 08-25-50 Dev Geeks | 
| **AFTER** | Screenshot 2023-07-27 at 08-10-50 Dev Geeks | 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
@TusharKesarwani, @pranjay-poddar, @Saurabh-kumar09 & @MohitGupta121 Your all reviews are appreciated.

**Comment by 0xabdulkhalid** [comment]
# Note to the reviewer 🚨 
- This PR comes under `level3` change because this is one of the core contribution to this project which adds up a new feature of getting live repository statistics from Github using GraphQL API.
- Additionally the code has been refactored too, and revamped the styles of the elements too.
- You can further refer this manual [here](https://cdn.discordapp.com/attachments/1099745008157986889/1112784850131357706/image.png) for more details about adding level labels to PR.

**Comment by Killer2op200** [comment]
**@0xabdulkhalid  In this era of rat race don't pollute the Open Source First the fall its come under level 1 because you just change the text color change the line of code not count as contribution hope so you understand** 

and Project admins i am from GSSoC Pr team don't trust on this img its not offcial

**Comment by 0xabdulkhalid** [comment]
@Killer2op200 How can you say that's this is just gimmick ?

Please don't lie that you're from PR Team, If you're realy from the Team then you don't want create a Fake Account for that.

I've researched and put so much of efforts to make this PR, the code works well.

It shows live statistics, you can verify the JavaScript file found on the `Changed files` section on this PR.

### Reviewers, you can once merge this if this really works you can give `level3` otherwise don't give any labels for this.

I'm so disappointed about how fellow participants creating fake accounts to track one's progress and blaming their instead of improving their contribution.

@gurjeetsinghvirdee need to be verify this PR, to prove that this is eligible one.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
