### PR TITLE
added Algorithm_learner

### LINKED ISSUE #3524: [GSSOC'23]: Algorithm learner using c++
**Describe the project you want to add with tech stack**
The project will help users understand various DSA algorithms 

**Expected behavior**
A brief explanation of the algorithms along with display of working will be added for better understanding.
Algorithms included-:
1. Sorting Algorithms-:
   i. Bubble Sort
   ii. Insertion Sort
   iii. Selection Sort
3. Searching Algorithms
   i. Linear Search
   ii. Binary Search

### PR DESCRIPTION
**Pull request by Nikita06211**
# Algorithm Learner using c++ and #3524

Close #3524

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Nikita06211** [comment]
@MohitGupta121 sir kindly review and merge this PR

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Change the folder to cpp projects folder

**Comment by Nikita06211** [comment]
@pranjay-poddar sir the Algorithms_learner folder is already present in cpp projects folder. Do you want me to remove this separate folder for Algorithms_learner  within cpp projects?

**Comment by Nikita06211** [comment]
@MohitGupta121 @pranjay-poddar sir kindly review the requested changes, as algorithm learner is already present in cpp projects folder.

**Pull request closed without merging**
