### PR TITLE
Frontend-Project "Youtube_clone" All Section Design Improvement

### LINKED ISSUE #2451: Frontend-Project "Youtube_clone" All Section Design Improvement
**Describe the Feature you want to end**
The current design is nice but it can be improved by making the 'All categories' section more like the youtube section. By doing some styling work, I can make this section look even better.

**Expected behavior**
More realistic and detailed look as of real youtube

**Screenshots (optional)**
Current Design
Youtube-clone (1)

Expected Updated Design
Youtube-clone (2)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
This PR contains the modified code for the frontend project "Youtube_clone All Section" design improvement. This PR is the result of the following issue:
Frontend-Project "Youtube_clone" All Section Design Improvement #2451

Close #2451

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
> @Saurabh-kumar09 @pranjay-poddar Kindly review this PR so that I can publish other issues PR.

Kindly review it

**Comment by iamRabia-N** [comment]
@MohitGupta121

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N are you spamming there is no file change.

**Comment by iamRabia-N** [comment]
@MohitGupta121 This isn't empty. Check this out.
ss (2)

**Comment by iamRabia-N** [comment]
@MohitGupta121 Checkout these changes in the commit named "Frontend-Project "Youtube_clone" All Section Design Improvement"
ss (3)

**Comment by iamRabia-N** [comment]
Output of the changes that were made in the commit. 
ss (4)

**Comment by iamRabia-N** [comment]
@MohitGupta121 Here's the problem. I created 2 PRs together. Although their branches were different but changes of 2nd PR also brought in the 1st branch. You merged my 1st PR few hours ago and this 1st PR contains the 2 issues solutions. So, that's why "No File Change" is showing in 2nd PR because these changes are already merged. I didn't know about this. Now, I will take care of this in future. I request you to reopen it and merged it as this PRs changes are merged. Kindly give me credit of the work that is merged already.
ss (5)
Link of merged PR:
Search Area Design Improvement #836
You can checkout this merged PR's commits as evidences

**Comment by iamRabia-N** [comment]
@MohitGupta121

**Comment by iamRabia-N** [comment]
@MohitGupta121

**Comment by iamRabia-N** [comment]
@MohitGupta121 @Saurabh-kumar09

**Comment by iamRabia-N** [comment]
@MohitGupta121

**Comment by MohitGupta121** [comment]
@iamRabia-N See there is no FIle change, please make a new PR for this issue and TAG me I will look into it. Thanks!



Screenshot 2023-07-01 at 1 51 59 PM

**Pull request closed without merging**
