### PR TITLE
Chat bot

### LINKED ISSUE #1347: Chat bot
**Describe the project you want to add with tech stack**
Chat bot with floating button option, which will help the user to add this chat bot in any already existing website.
Tech Stacks used are - HTML, CSS, Vanilla JS, API

**Expected behavior**
Can answer any question as it fetches info from openAI APP

**Screenshots (optional)**
image

### PR DESCRIPTION
**Pull request by Prakhar-Shankar**
# Title and Issue number 
Title - Chatbot 
Issue number #1347 

Close #1347 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Prakhar-Shankar please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Prakhar-Shankar Also Please move your whole project to their respective project folder as mentioned in [repo](https://github.com/pranjay-poddar/Dev-Geeks/pull/2005). Thanks!

**Comment by Prakhar-Shankar** [comment]
https://github.com/pranjay-poddar/Dev-Geeks/assets/97254881/25d79cdd-4fd1-4d95-b2fe-2bdb3945b38d

Here's the screen recording

**Comment by MohitGupta121** [comment]
@Prakhar-Shankar for every type of project there is a folder in DEV-GEEKs for every specific project. So put your this project in that particular folder, Thanks!

**Comment by Prakhar-Shankar** [comment]
> @Prakhar-Shankar for every type of project there is a folder in DEV-GEEKs for every specific project. So put your this project in that particular folder, Thanks!

Hey, I have little issue in doing this can you please guide me through this .
Thanks!

**Comment by MohitGupta121** [comment]
@Prakhar-Shankar just move this project whole Project folder into this folder - https://github.com/pranjay-poddar/Dev-Geeks/tree/main/Js-Projects

**Pull request closed without merging**
