### PR TITLE
Added Form Validation Website

### LINKED ISSUE #2491: Form Validation Website
**Describe the project you want to add with tech stack**
A Form Validation Website , having input fields like name, email, password, etc. It is used to prevent errors by checking the data entered by the user for errors such as empty fields, invalid characters.Ensures the data is accurate. Prevent the mistakes of user inputing wrong data/format by giving errors.

**Expected behavior**
Provides accurate data to be filled.

**Screenshots (optional)**
image

### PR DESCRIPTION
**Pull request by Ayushkumargit7**
# Title and Issue number 
Form Validation Website
Issue #2491
Close #2491

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Ayushkumargit7** [comment]
Add the gssoc23 label and level label.

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Two projects are committed in one PR, please check

**Comment by Ayushkumargit7** [comment]
I created different pr,for before project.
And I created separate branch for this new project ,then also that old one is showing here.

**Comment by Ayushkumargit7** [comment]
Can you merge that before space invaders PR ,https://github.com/pranjay-poddar/Dev-Geeks/pull/2419
Then I can delete that branch and commit to this project from main branch .

**Pull request closed without merging**
