### PR TITLE
Frontend Project "TBT" Explore Destination Button Design Enhancement

### LINKED ISSUE #3410: Frontend Project "TBT" Explore Destination Button Design Enhancement
**Describe the Feature you want to end**
Changing few styling properties to make it look even better.

**Expected behavior**
Smooth styled button design.

**Screenshots (optional)**

Current Design
tour-web (6)

Expected Updated Design
tour-web (5)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project "TBT" Explore Destination Button Design Enhancement
Close #3410

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pr.

**Comment by MohitGupta121** [comment]
@iamRabia-N I approving your this small small PR's now next time please add your changes recording BEFORE and AFTER recording then I'll approve your PR. Thanks!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N PTAL

**Comment by iamRabia-N** [comment]
@MohitGupta121  Done with updating branch

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
