### PR TITLE
Sealed Secret (NoteTaker)

### LINKED ISSUE #2024: Adding a front-end project: NoteTaker[gssoc23]
**Describe the project you want to add with tech stack**

A website which allows you to keep all your secret notes.
Tech Stake- HTML, CSS, JAVASCRIPT, JQUERY.
**Expected behavior**

**Screenshots (optional)**

Screenshot (227)

Screenshot (228)

Screenshot (229)

Screenshot (230)

Screenshot (231)

**Additional context (optional )**

Please add the tag of gssoc23

### PR DESCRIPTION
**Pull request by thevirengarg**
# Title and Issue number 

Front-end Project: NoteTaker (Sealed Secret) [gssoc23]
Please add the tag of gssoc23. 

Close #2024 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/111726483/26bafe1e-5e64-4380-a208-e13033c3013d

### CODE REVIEW

**Comment by thevirengarg** [comment]
@MohitGupta121 @pranjay-poddar Please review this PR.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@thevirengarg please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your images, images/videos in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.
Thanks!

**Comment by thevirengarg** [comment]
@MohitGupta121 Please review this PR. I have made all the changes requested by you.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
