### PR TITLE
Calculator with Light and Dark Mode

### LINKED ISSUE #1760: GSSOC'2023 Project Calculator with Light and Dark Mode.
**Project Calculator with Light and Dark Mode using Javascript, HTML5 and CSS.**

**The modes of the environment can be switched to Light or Dark.**

### PR DESCRIPTION
**Pull request by RoopakMallik**
Calculator with Light and Dark Mode #1760 
Close #1760 
Fixed issue #1760 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

Screen Recording of the project -

https://github.com/pranjay-poddar/Dev-Geeks/assets/70304320/99d6a286-574c-4dd1-9b84-22a94950ff12

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@RoopakMallik please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by RoopakMallik** [comment]
Could you please elaborate on the 'screen recording' part of the issue.
Also since the issue has been assigned to me now, do I need to make another
pull request?

**Comment by MohitGupta121** [comment]
@RoopakMallik screen recording for your changes, for your output code or site.

**Comment by RoopakMallik** [comment]
I have fixed the PR and updated it with the Screen Recording as asked.

**Comment by RoopakMallik** [comment]
> @RoopakMallik screen recording for your changes, for your output code or site.

@MohitGupta121 I have updated the PR and added the screen recording as asked.

**Review by MohitGupta121 — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
