### PR TITLE
Drum sound Project Added

### PR DESCRIPTION
**Pull request by Nayan808**
Hello Project Admin,
## Screenshot -
Screenshot from 2023-06-25 15-08-55

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by Nayan808 — COMMENTED** [review]
ALL Files Are Checked its Super Ready To merge

**Review by MohitGupta121 — APPROVED** [review]
@Nayan808 from next time please use the PR template.

**Comment by Nayan808** [comment]
Okay I will remove the other files I will only go with drum sound web app sorry for the inconvenience

**Comment by Nayan808** [comment]
I Apologise For This I will Push The Reposirory Soon

**Pull request closed without merging**
