### PR TITLE
flash game

### LINKED ISSUE #1832: Flash Game
**Describe the project you want to add with tech stack**
Made using Frontend Languages like HTML , CSS and Javascript. It is a Flash game which consists of Pictures which appears like a flash and and a question is asked with a timer and 4 options. The image appeared before is the hint to the answer.

**Expected behavior**
It is a Flash game which consists of Pictures which appears like a flash and and a question is asked with a timer and 4 options. some features are 
Timers
Sound effect
Restarted with reloading.
Scorelist

**Screenshots (optional)**
Screenshot 2023-06-04 194230
Screenshot 2023-06-04 194253

**Additional context (optional )**

I am the GSSoc'23 contributor plz assign this to me.

### PR DESCRIPTION
**Pull request by Shreya111111**
# Title and Issue number 
flash game

Close #1832 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

https://github.com/pranjay-poddar/Dev-Geeks/assets/95047638/c6ddb206-5848-46f2-bbdb-dec80313c1e5

### CODE REVIEW

**Comment by Shreya111111** [comment]
@Saurabh-kumar09  plz review this issue #1832 and PR #1853

**Comment by Shreya111111** [comment]
@Saurabh-kumar09  It has been 3 days since I linked my PR ..PLZ check I have also added the screenshots for the reference

**Comment by Shreya111111** [comment]
@MohitGupta121  I will add the same

**Comment by MohitGupta121** [comment]
@Shreya111111 please add in the PR description.

**Comment by Shreya111111** [comment]
issue https://github.com/pranjay-poddar/Dev-Geeks/issues/1832 and PR https://github.com/pranjay-poddar/Dev-Geeks/pull/1853
@MohitGupta121 I have added the screenrecording ...as the screenrecording was big I cut some part hope u get that
https://github.com/pranjay-poddar/Dev-Geeks/assets/95047638/4ae912aa-35ed-4eaa-a2ea-0da6e5539329

**Review by MohitGupta121 — APPROVED** [review]
LGTM, Thanks

**Pull request merged**
