### PR TITLE
made balloon splash game using js and added it to the folder

### PR DESCRIPTION
**Pull request by pranayjalan254**
made this game using javascript. please merge this pull request thank you

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
Pls follow the folder hierarchy, put all JavaScript game in already present jsgames folder

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Move files to JS-Games folder

**Comment by pranayjalan254** [comment]
okay will do the same thank you

**Comment by pranayjalan254** [comment]
will make another pull request for the same in the folder heirarchy

**Pull request closed without merging**
