### PR TITLE
LOGIN SYSTEM FULL STACK

### PR DESCRIPTION
**Pull request by RJ025**
login system full stack

tech used: html css javascript nodejs expressjs

### CODE REVIEW

**Comment by RJ025** [comment]
@pranjay-poddar

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
move your project files to one folder and move that folder under MERN folder

**Comment by RJ025** [comment]
@pranjay-poddar  so should i generate another PR

**Comment by pranjay-poddar** [comment]
Just push the code with changes PR will automatically update

**Pull request closed without merging**
