### PR TITLE
added youtube clone

### LINKED ISSUE #2705: Added a Youtube Clone
# **Describe the project you want to add with tech stack**
I will be adding a Youtube Clone 
The clone will be made in Python, Flask, etc
# **Expected behavior**
It will fetch youtube data using API and then displays the video on the webpage
# **Screenshots (optional)**
image

Please assign me this issue under GSSOC'23

### PR DESCRIPTION
**Pull request by Swapnil-Singh-99**
# Youtube Clone and #2705 

Close #2705 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

# Screen Recording
[Screencast from 12-07-23 04:42:56 PM IST.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/85278243/697391d1-35ef-44ff-aef7-acacd0daef11)

### CODE REVIEW

**Comment by Swapnil-Singh-99** [comment]
@TusharKesarwani Please review the PR

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Add your project to the Front-End Project folder

**Review by TusharKesarwani — APPROVED** [review]

**Comment by Swapnil-Singh-99** [comment]
@TusharKesarwani I have made the changes

**Comment by Swapnil-Singh-99** [comment]
@TusharKesarwani Please add gssoc23 and level2/level3 label

**Pull request merged**
