### PR TITLE
Add Google Docs Clone

### LINKED ISSUE #1491: [GSSOC'23] Google Docs Clone
**Describe the project you want to add with tech stack**
An application working on the lines of Google Docs. Sockets IO used for connecting between client and server. ReactJS is used as a frontend, QuillJS for editor, NodeJS as backend, Socket IO and MongoDB database. 

**Expected behavior**
It can save files automatically and also if a file is shared with someone then anyone can make changes in it. 

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/91741581/3c97a165-6976-4394-8714-9cae8f5b72f1

**Additional context (optional)**
Please assign me this for GSSoC'23.

### PR DESCRIPTION
**Pull request by Vidip-Ghosh**
Added a new Project Google Docs Clone
#1491 

Close #1491 

https://github.com/pranjay-poddar/Dev-Geeks/assets/91741581/10107a83-c6b2-4c45-a687-a2e382ba1c24

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Files are not committed properly

**Comment by Vidip-Ghosh** [comment]
Now can you please review if everything is alright?

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Vidip-Ghosh please resolves conflicts

**Comment by Vidip-Ghosh** [comment]
> @Vidip-Ghosh please resolves conflicts

Yes I have resolved conflicts. Now check if its alright.

**Review by MohitGupta121 — APPROVED** [review]

**Review by pranjay-poddar — APPROVED** [review]

**Pull request merged**
