### PR TITLE
Frontend Project's "Learning_Webpage: About Our Services" Section Updated Design

### LINKED ISSUE #1548: Frontend Project's "Learning_Webpage: About Our Services" Section Design Improvement
### **Describe the Feature you want to end**
I want to add hover effect in the **"About Our Services"** Section of this website. Changing color, margin, background, and other style properties on the **"more"** button to make it look even better

### **Expected behavior**
An attractive UI of this section which feels realistic and natural in terms of designing

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project's "Learning_Webpage: About Our Services" Section Design Improvement #1548

Close #1548

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
> # Title and Issue number
> Frontend Project's "Learning_Webpage: About Our Services" Section Design Improvement #1548
> 
> Close #1548
> 
> # Checklist:
> * [x]  I have mentioned the issue number in my Pull Request.
> * [x]  I have commented my code, particularly in hard-to-understand areas
> * [x]  I have created a helpful and easy to understand `README.md`

@Saurabh-kumar09 Kindly review this PR

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this PR. There are two more issues in pending and I can't publish their code as they are merging in this PR as commits although branches are separate.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by iamRabia-N** [comment]
### Current Design
learning_webpage (2)

### Updated Design with Addition of Hover Effect on Boxes
learning_webpage (3)

### Updated Design with Addition of Hover Effect on Button
learning_webpage (1)

Other than this, the font-size difference also come when user hover the boxes.

@MohitGupta121 Kindly review the screenshots and share your feedback.

**Review by MohitGupta121 — APPROVED** [review]
@iamRabia-N LGTM, Thanks!

**Pull request merged**
