### PR TITLE
[GSSoC'23] Added a dad jokes generator to frontend projects

### LINKED ISSUE #1947: [GSSoC'23]: Add a new frontend project called Dad Jokes Generator
**Describe the project you want to add with tech stack**

Add a new Dad Joke Generator using HTML, CSS and JavaScript to Frontend projects.

**Expected behavior**

On clicking the button "Tell me a joke", a joke will be displayed on the screen. On clicking it again, the current joke will disappear and a new joke will appear in its place.

**Screenshots (optional)**

image

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by SoarinSkySagar**
# [GSSoC'23]: Add a new frontend project called Dad Jokes Generator #1947

Close #1947 

Screen recording:

https://github.com/pranjay-poddar/Dev-Geeks/assets/117727361/caa278d7-51c7-4291-ae89-2b0fb033c03b

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by SoarinSkySagar** [comment]
@pranjay-poddar @MohitGupta121 @Saurabh-kumar09 please review and merge the PR

issue: #1947 
PR: #1952

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@SoarinSkySagar LGTM, Thanks

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

@MohitGupta121 I have added the screen recording in the PR description. Please review and merge now, if it is okay. Also, there is already a screenshot given in issue itself (#1947)

**Comment by SoarinSkySagar** [comment]
@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
