### PR TITLE
PDF to TXT

### PR DESCRIPTION
**Pull request by Avik-creator**
It closes the issue #241

### CODE REVIEW

**Comment by Avik-creator** [comment]
@pranjay-poddar please check it

**Comment by pranjay-poddar** [comment]
Add screenshots in PR

**Comment by Avik-creator** [comment]
https://user-images.githubusercontent.com/77090462/180646375-b0305c4a-1dbf-4436-a20a-455d6e1600fe.mov

@pranjay-poddar Please check it

**Comment by Avik-creator** [comment]
@pranjay-poddar please check

**Pull request merged**
