### PR TITLE
Change in radio button position

### LINKED ISSUE #1427: Update the radio button in one line
**Describe the Feature you want to end**
 To make the options in one line 

**Expected behavior**
So it will look more attractive and user friendly.

**Screenshots (optional)**
Screenshot (157)

**Additional context (optional )**
I want to work on it please assign this issue to me

### PR DESCRIPTION
**Pull request by Shiwani2002**
# Fixes issue #1427 

Close #1427

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shiwani2002 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Shiwani2002** [comment]
Ok

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shiwani2002 also resolves PR conflicts. Thanks!

**Comment by Shiwani2002** [comment]
Ok

**Comment by Shiwani2002** [comment]
Screenshot (57)

**Comment by Shiwani2002** [comment]
I have changed in radio button position.

**Comment by Shiwani2002** [comment]
actually i  want to know that you did not merge my pull request .If there is any problem then i can resolve that. Please reply @MohitGupta121

**Comment by MohitGupta121** [comment]
@Shiwani2002 which PR, this PR is closed by you not me.

**Comment by MohitGupta121** [comment]
Create a new PR for the issue and TAG me.

**Comment by Shiwani2002** [comment]
I have  done new pull request .Please merge this @MohitGupta121

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shiwani2002 please resolve conflicts then it's ready to merge.

**Comment by Shiwani2002** [comment]
ok

**Comment by Shiwani2002** [comment]
@MohitGupta121 please give me the access so that i can resolve the issue

**Comment by Shiwani2002** [comment]
@MohitGupta121 please give me the access so that i can resolve the conflict

**Comment by MohitGupta121** [comment]
@Shiwani2002 for resolving conflicts there is no need of access, it's just a branch update from your end and push updated code. That's it.

**Pull request closed without merging**
