### PR TITLE
Added the Rabbit rush Game

### LINKED ISSUE #1697: [NEW GAME][GSSOC'23] Rabbit Rush Game
A retro styled game testing your reflexes and precision on the keyboard or mouse. Your main aim is to save the rabbit from the wolf running behind him to catch him. You can do it by jumping the rabbit over the hedgehogs that come in his path and by grabbing the carrots that increase its speed.

**Screenshots (optional)**

rabbit

### PR DESCRIPTION
**Pull request by aditya-agr**
# Rabbit Rush and Issue No : #1697 

Rabbit Rush 
Issue No : #1697 

Close #1697

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by aditya-agr** [comment]
Resolved the requested changes

**Comment by aditya-agr** [comment]
@pranjay-poddar please review it and merge it

**Comment by aditya-agr** [comment]
Also add the labels of gssoc and level

**Comment by MohitGupta121** [comment]
@pranjay-poddar  please appprove this PR.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@aditya-agr please resolves conflicts

**Comment by aditya-agr** [comment]
@MohitGupta121 the conflicts are again resolved. Please review and merge it.

**Comment by aditya-agr** [comment]
Also add the labels of gssoc23

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
@pranjay-poddar please merge and approve this PR.

**Comment by aditya-agr** [comment]
Also add the labels of gssoc23

**Pull request closed without merging**
