### PR TITLE
simple to do list using angularJS

### LINKED ISSUE #14: Add angular Project
Add angular mini-projects in angular folder.

### PR DESCRIPTION
**Pull request by Subha-5**
**Project Name** : to do list

This completes and closes #14
  
The project is made using angularJS , a frontend frameword developed by Google 

Screenshot (206)
Screenshot (209)

### CODE REVIEW

**Comment by Subha-5** [comment]
@pranjay-poddar  this completes the task given in issue #14 . You may close this issue.

**Comment by Subha-5** [comment]
@pranjay-poddar please review this issue.

**Comment by pranjay-poddar** [comment]
> @pranjay-poddar this completes the task given in issue #14 . You may close this issue.

add this issue number with the PR and not as a separate comment

**Comment by Subha-5** [comment]
> > @pranjay-poddar this completes the task given in issue #14 . You may close this issue.
> 
> add this issue number with the PR and not as a separate comment

@pranjay-poddar  Done

**Pull request merged**
