### PR TITLE
Added EditorJS to Node.js Projects

### LINKED ISSUE #1816: Add Editorjs Project
**Describe the project you want to add with tech stack**
Hey @pranjay-poddar I want to add the editorjs project to your repo. Please assign me this issue. Thank you!

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by sumitkr2000**
# Title and Issue number 
Hey @pranjay-poddar I have added the EditorJS project to the Node.js folder. Please review my pr and merge it. Thank you!

Close #1816 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@sumitkr2000 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

Also please avoid to push package-lock.json

**Comment by sumitkr2000** [comment]
[screen-capture (1).webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/4f65011c-eda4-4361-9c15-6ba8ad1a6e6c)


@MohitGupta121

**Comment by MohitGupta121** [comment]
@sumitkr2000 please add project demo live run video recording.

**Comment by sumitkr2000** [comment]
[screen-capture.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/100675296/cec1048d-93a8-4319-ab16-c8d7898afba2)


@MohitGupta121

**Review by MohitGupta121 — APPROVED** [review]
@sumitkr2000 LGTM, Thanks!

**Pull request merged**
