### PR TITLE
Frontend Project "PrimeFlix" 'Your favorite channels all in one place' Section Styling

### LINKED ISSUE #3644: Frontend Project "PrimeFlix" 'Your favorite channels all in one place' Section Styling
**Describe the Feature you want to end**
Changing few styling properties of this section to improve its design.

**Expected behavior**
Improved design of this section.

**Screenshots (optional)**

Current Design
ip (4)

Expected Updated Design
ip (3)

**Additional context (optional )**
N/A

### PR DESCRIPTION
**Pull request by iamRabia-N**
# Title and Issue number 
Frontend Project "PrimeFlix" 'Your favorite channels all in one place' Section Styling
Close #3644 

# Output

**Before**
op (6)

**After**
op (31)

# Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamRabia-N** [comment]
@MohitGupta121 Kindly review this pull request.

**Comment by iamRabia-N** [comment]
Hi @MohitGupta121
Kindly review this pull request so that I can work on other issues.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N please resolve confilcts

**Comment by iamRabia-N** [comment]
> @iamRabia-N please resolves conflicts

@MohitGupta121 Done with resolving conflicts. You can review now.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@iamRabia-N still conflicted

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
