### PR TITLE
Lee Cooper Clone added 

### LINKED ISSUE #711: Lee Cooper Website Clone
**Describe the project you want to add with tech stack**
official Lee Cooper Website Clone

**Expected behavior**
Website clone with all the functionality

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by RAHULBAWA777**
# Title and Issue number 
Lee Cooper Clone  #711 

Close #<issue_no>
closes #711

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Move your project to frontend projects folder

**Comment by RAHULBAWA777** [comment]
> Move your project to frontend projects folder

I did it bro... Please approve my prs now... Check it I've pushed it to the correct folder

**Comment by RAHULBAWA777** [comment]
Bro I'm new to git hub... Please compromise a bit... I made a new pr and pushed every pr to the front end folder.... Now I have no idea how to undo the things and do what you are asking

**Comment by MohitGupta121** [comment]
Closing as part of Hacktoberfest 2021 and now outdated.

**Pull request closed without merging**
