### PR TITLE
Guess the color #1931

### LINKED ISSUE #1931: Guess the color game
**Describe the project you want to add with tech stack**

Color Guess" is a simple game that tests the player's ability to recognize colors based on their RGB values. The game presents the player with a set of color options, one of which matches the displayed RGB values. The player needs to select the correct color to win the game.

**Expected behavior**
If the player selects the correct color, a success message is displayed, indicating that they have won the game. If the player selects the wrong color, a try again message is shown, encouraging them to make another attempt.

The player can also click the "New Colors" button to reset the game. This generates a new set of colors and picks a new target color for the player to guess.
Screenshot (230)

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by prachisingh1008**
https://github.com/pranjay-poddar/Dev-Geeks/assets/89354933/b33d61d7-63a4-4b51-8804-ff00c62bdac9

# Title and Issue number 

Close #1931

# Checklist:

- [x] I have mentioned the issue number in my Pull Requ
Screenshot (230)
est.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@prachisingh1008 please add screen recording for your changes in PR description. Thanks!

**Review by MohitGupta121 — APPROVED** [review]
@prachisingh1008 LGTM, Thanks

**Comment by pranjay-poddar** [comment]
Reverting merge,
Please commit the project files inside the particular folders and avoid committing in the root folder.

**Comment by prachisingh1008** [comment]
SORRY FOR THE INCONVENIENCE !
DO I NEED TO COMMIT CHANGES AGAIN FOR MERGING MY REQUEST

**Pull request merged**
