### PR TITLE
Adding DigiClock Website in Cpp 

### PR DESCRIPTION
**Pull request by Nayan808**
Hey! Admin I had Completed My Work  dIgital clock by `cpp`

### CODE REVIEW

**Comment by Nayan808** [comment]
@MohitGupta121 @TusharKesarwani

**Review by MohitGupta121 — APPROVED** [review]

**Comment by MohitGupta121** [comment]
@Nayan808 where is the issue number?

**Comment by Nayan808** [comment]
@MohitGupta121 i dont got points for the merge pleae help me !

**Comment by Nayan808** [comment]
hi My pull request  is merged but i have not got points @MohitGupta121 @TusharKesarwani @PoulavBhowmick03

**Pull request merged**
