### PR TITLE
Issue 1956

### LINKED ISSUE #1956: Interactive Rating Component
**Describe the project you want to add with tech stack**

Interactive Rating Component using HTML and CSS in Frontend-Projects

## Issue Type:
- [x] New Project

## **Screenshots**
mow7ca07z3qa0ffbwc2p

### PR DESCRIPTION
**Pull request by MisterMickey**
# Rating Component

Close #1956 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

mow7ca07z3qa0ffbwc2p

### CODE REVIEW

**Review by pranjay-poddar — APPROVED** [review]

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Resolve branch conflicts

**Comment by pranjay-poddar** [comment]
Branch conflicts are not resolved

**Comment by MisterMickey** [comment]
@pranjay-poddar Resolved.

**Comment by pranjay-poddar** [comment]
Closing due to unresolved branch conflicts

**Pull request closed without merging**
