### PR TITLE
Added Student Manager API 

### LINKED ISSUE #2524: Student Manager API in NodeJs
**Describe the project you want to add with tech stack**
A Student Manager API having the CRUD operations using MongoDB and Node.js

**Tech Stack**
Javascript ( Nodejs, Express.js )
MongoDB

**Expected behavior**
This would be a database for managing student data like roll no, name, email, and other details.
We would do GET, POST, PUT, and DELETE requests to /api/students/ to interact with db.

### PR DESCRIPTION
**Pull request by vishnuprasad2004**
# Title and Issue number 
issue number #2524 
Added Student Manager API in NodeJs Projects with CRUD operations using the student's roll number.
## Used
NodeJs, ExpressJs, MongoDB

Close #2524 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by vishnuprasad2004** [comment]
@MohitGupta121 please merge this pr

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@vishnuprasad2004 why are you adding 2 projects if it's a Student management project then why there is Text to Speech also? Add only 1 project in 1 PR.

**Comment by vishnuprasad2004** [comment]
Accidentally added two projects in 1 pull request.

**Comment by MohitGupta121** [comment]
@vishnuprasad2004 make new clean PR.

**Comment by vishnuprasad2004** [comment]
Ok

**Pull request closed without merging**
