### PR TITLE
Added the envelop opening animation

### LINKED ISSUE #4779: envelop opning animation
**Describe the project you want to add with tech stack**

its an amazing envelop opening animation

**Expected behavior**

**Screenshots (optional)**

https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/2d706b0b-f579-4af7-9e95-25002b921e75

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by abansal15**
#4779 

Close #4779 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121  @TusharKesarwani  please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani please review it

**Comment by abansal15** [comment]
@MohitGupta121  @TusharKesarwani  please review it asap

**Review by TusharKesarwani — APPROVED** [review]

**Pull request merged**
