### PR TITLE
House Price Prediction with Docker

### LINKED ISSUE #2254: House Prediction and deploying it with Docker
**Describe the project you want to add with tech stack**
House Prediction and deploying it with docker and Github Actions

**Expected behavior**
It Predicts the house price in Boston.

**Additional context (optional )**
GSSOC '23

### PR DESCRIPTION
**Pull request by Mochoye**
# House Prediction and deploying it with Docker [#2254]

Close #2254

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

# Screenshot

### CODE REVIEW

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Do not upload files in submodules

**Comment by Mochoye** [comment]
Can you please guide me like what to change, bit unable to understand. Can i ping you in discord?

**Review by Mochoye — COMMENTED** [review]
What to do i cant see any files can you please guide me?

**Comment by Mochoye** [comment]
So shall i close this PR and create a new PR?

**Pull request closed without merging**
