### PR TITLE
Bus tracker react app

### LINKED ISSUE #1723: Bus Tracker (Gssoc'23)
**Describe the project you want to add with tech stack**
This is a simple react app made to track the buses route.

**Expected behavior**
* It has one college icon at the centre and 12 buses marked with their respective numbers on them.
* When we hover on the buse icons driver's name and number appears which makes it easier for the students to track their buses on their own.
* Also there is a start and destination point and stops set in between the route of the bus which gets highlighted when we click on it.

**Screenshots (optional)**
image

### PR DESCRIPTION
**Pull request by kadambari68**
# Title and Issue number 
Bus Tracker (Gssoc'23) Issue #1723 

Close #1723

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Saurabh-kumar09** [comment]
@kadambari68 Please check the files you have committed. Looks like there are multiple projects you have committed. Make the changes or, close this PR. And make a new PR.

**Comment by kadambari68** [comment]
Do I need to cline the project every time I create a new branch and add a new project

**Comment by Saurabh-kumar09** [comment]
No, that's not needed

**Comment by Saurabh-kumar09** [comment]
If you are facing any problem, share it in discord channel. I'll look.

**Comment by kadambari68** [comment]
How can I make changes in this PR and remove the other 2 commits

**Comment by Saurabh-kumar09** [comment]
You can delete those files. OR,
Close this PR, and make a new PR with proper commit. It would be better.

**Comment by kadambari68** [comment]
It would be ok if I use the se branch

**Comment by Saurabh-kumar09** [comment]
Yes you can.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@kadambari68 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by MohitGupta121** [comment]
inactive

**Pull request closed without merging**
