### PR TITLE
Issue 4532 Made the circular animation

### LINKED ISSUE #4532: circular random animation only html and css
https://github.com/pranjay-poddar/Dev-Geeks/assets/120590200/10879113-d503-40f3-b679-1ef91636d110

### PR DESCRIPTION
**Pull request by abansal15**
#4532 

Close #4532 >

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani  please review it

**Comment by abansal15** [comment]
@MohitGupta121 @TusharKesarwani  please review it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@abansal15 please upload only 1 project in your PR there are currently multiple project here.

**Review by abansal15 — COMMENTED** [review]
done now only one project

**Comment by abansal15** [comment]
@MohitGupta121 now there is only single project in this pr

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
