### PR TITLE
Make simple calculator using Python

### LINKED ISSUE #2537: Calculator
I would like to make a simple calculator using python .

GSSOC -23

### PR DESCRIPTION
**Pull request by gkm0001**
fixes #2537

# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by 0001skm — APPROVED** [review]

**Comment by 0001skm** [comment]
Merge the pull request.

**Review by 0001skm — APPROVED** [review]
Thank you for contributing.

**Review by 0001skm — APPROVED** [review]
thank you

**Review by 0001skm — APPROVED** [review]
Thank you for contributing.

**Review by 0001skm — APPROVED** [review]

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
