### PR TITLE
Added Jarvis Powered voice assistant project 

### LINKED ISSUE #3390: Jarvis and OpenAI Powered voice-AI assistant using Python
**Describe the project you want to add with tech stack**
Using tools like OpenAi's chat-gpt, users can get written answers to almost any question. I'd make use of Jarvis and create a voice-assistant in python which would talk to the user and would answer questions. 

**Tech Stack:** OpenAI, Jarvis, Python

**Expected behavior**
- User can start the conversational assistant by running the program. 
- The voice assistant would start by a greeting from Jarvis. 
- User chats via voice medium with Jarvis as long as the user wants to. 
- User can terminate the program via voice itself.

### PR DESCRIPTION
**Pull request by jaivsh**
# Implemented the Jarvis powered voice assistant in Python Projects 

This is a voice assistant with which one can interact with one-on-one and can chat or query any voice based response. It is made from over a dozen python libraries.

Close #3390 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by jaivsh** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar please review my PR.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jaivsh please resolves conflicts

**Comment by jaivsh** [comment]
@MohitGupta121 done!

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@jaivsh please resolves conflicts

**Comment by jaivsh** [comment]
> @jaivsh please resolves conflicts

Hi @MohitGupta121 I've resolved the issues. Please check PR

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
