### PR TITLE
Mexico Escape and Microsoft clone

### LINKED ISSUE #1933: [Game] : Maxico Escape (GSSoC'23)
Demo vedio:

https://github.com/pranjay-poddar/Dev-Geeks/assets/98798977/32c7f83a-d52a-4405-bf07-abd487937691

Techology Used:
HTML
CSS
Javascript

### PR DESCRIPTION
**Pull request by Durgesh4993**
# Title and Issue number 

Close #1933 and #1934

Demo vedio:

https://github.com/pranjay-poddar/Dev-Geeks/assets/98798977/32c7f83a-d52a-4405-bf07-abd487937691

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Durgesh4993** [comment]
@pranjay-poddar could you please review the code if you need any changes please describe

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Durgesh4993  please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increase the whole Dev-Greek project size.
Thanks!

**Comment by MohitGupta121** [comment]
> @MohitGupta121 ok i'll try to reduce the size of code

Please only remove direct use of images, fetch images from cloud or use images URL link in your project.

**Comment by Durgesh4993** [comment]
Ok sir

**Pull request closed without merging**
