### PR TITLE
portfolio

### PR DESCRIPTION
**Pull request by radhika2503**
# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by radhika2503** [comment]
Title - portfolio. Issue number - #692 
Please merge it under hacktoberfest2022

Close #697

**Comment by radhika2503** [comment]
Title -portfolio. Issue number -#697
Please merge it under hacktoberfest2022

Close #697

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
move all your project file to a folder and move that folder in fronted projects

**Comment by MohitGupta121** [comment]
Closing as part of Hacktoberfest 2021 and now outdated.

**Pull request closed without merging**
