### PR TITLE
Added Stick Hero Game (#1569)

### LINKED ISSUE #1569: Stick Hero game
**Describe the project you want to add with tech stack**
Players will control a stick figure character who can extend and retract a stick to bridge gaps between platforms. The player's input, such as tapping or clicking, will determine the length of the stick.

**Expected behavior**
The player needs to accurately gauge the length of the stick and position it to reach the next platform without falling. The player must adjust the stick length to match the gap width and ensure the stick lands on the next platform securely. The game will end if the stick falls short of the platform or extends beyond it, resulting in the player's character falling.

**Screenshots (optional)**
image

### PR DESCRIPTION
**Pull request by Yashika-Agrawal**
# Title and Issue number 
Stick Hero Game (#1569 )

Close #1569 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — APPROVED** [review]

**Comment by killer2O** [comment]
@MohitGupta121 @Saurabh-kumar09 this is already merged in another project https://github.com/kunjgit/GameZone/pull/644

**Comment by Yashika-Agrawal** [comment]
@killer2O here it is also merged, you try to find another issues.

**Comment by killer2O** [comment]
> @MohitGupta121 @Saurabh-kumar09 this is already merged in another project [kunjgit/GameZone#644](https://github.com/kunjgit/GameZone/pull/644)



> @killer2O here it is also merged, you try to find another issues.

@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar Please remove the labels and mark this as spam as this very unfair to other contributers. Many other contributers are doing the same thing. Please take appropriate actions

**Comment by Yashika-Agrawal** [comment]
Bro it would be unfair if I would have stole other's contributor project both are mine projects. I have worked on it, and raised the issue first. Both the repositories require games , so i have added and not only me many are doing this, it's there projects.

**Pull request merged**
