### PR TITLE
Magic Notes a React app added issue #2953 

### PR DESCRIPTION
**Pull request by adityakmrmishra**
### Project title
MAGIC NOTES

### Project Description
It is a simple notes keeping project .
It is a REACT APP .
Project looks like 
magicNotes

Close issue #2953 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Adityamishra9719** [comment]
I had added a game name Anaconda a snake game .
It is made using HTML , CSS and JAVASCRIPT .
It is very easy to play as you only have to use up , down, left and right arrow to move snake for eating food and making high scores .
The game look like the below screenshot -
Screenshot 2023-07-11 124245

Close issue #2954

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

**Comment by Adityamishra9719** [comment]
pls merge these prs @pranjay-poddar

**Comment by TusharKesarwani** [comment]
Resolve conflicts

**Comment by Adityamishra9719** [comment]
> Resolve conflicts

Done

**Review by TusharKesarwani — CHANGES_REQUESTED** [review]
Do proper changes in the readme file
You're adding project 261 but project number 261 was already there

**Comment by Adityamishra9719** [comment]
> Do proper changes in the readme file You're adding project 261 but project number 261 was already there

Done

Screenshot 2023-08-05 140808

**Comment by adityakmrmishra** [comment]
Pls merge it

**Pull request closed without merging**
