### PR TITLE
Parking Lot Managements System

### LINKED ISSUE #3292: [NEW PROJECT] Parking Lot Management system
**Describe the Feature you want to end**
Parking Lot Management System which helps to store the details of the parked vehicles.Using HTML,CSS,JS,Bootstrap

**Expected behavior**
It helps in store vehicles number, type and owner, parking details.

**Screenshots (optional)**
Screenshot 2023-07-09 at 10 36 09 AM

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by SnigdhaP2022**
#3292 [NEW PROJECT] Parking Lot Management System 

Close #3292 

# Checklist:

- [✅] I have mentioned the issue number in my Pull Request.
- [✅] I have commented my code, particularly in hard-to-understand areas

Screenshot 2023-07-16 at 10 52 27 AM

### CODE REVIEW

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 Kindly,review this

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@SnigdhaP2022 remove all images from PR and upload them somewhere else then use from there link to fetch load the images.

**Comment by SnigdhaP2022** [comment]
@MohitGupta121 I have completed requested changes. Kindly,review and merge the project.

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  Kindly, review and merge the project file pleasee.

**Comment by SnigdhaP2022** [comment]
@MohitGupta121  @TusharKesarwani  Requested changes had been made. Kindly, review the file and merge the PR 🎉

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
