### PR TITLE
Improved the UI of the gym website and made it more feasible

### LINKED ISSUE #1897: To Improve the UI of the gym website and make it more feasible
I want to change the UI of this site and make it more user friendly 

The website would contain working features and a section to fill person details for getting contacted 

Before changes :-
 
WhatsApp Image 2023-06-08 at 00 00 58

 After changes :-

Screenshot 2023-06-07 233519

### PR DESCRIPTION
**Pull request by Shubham6621**
# To Improve the UI of the gym website and make it more feasible  #1897

Close #1897

# Checklist:

- [✔️] I have mentioned the issue number in my Pull Request.
- [✔️] I have commented my code, particularly in hard-to-understand areas
- [✔️] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Shubham6621 Please follow these things in your PR:

1. Please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increase the whole Dev-Greek project size.
2. Add video recording of your project site demonstration.
3. Also resolve conflicts of this PR.
Thanks!

**Comment by Shubham6621** [comment]
I have synced my fork with latest version , now please review my pull request.
image

**Comment by Shubham6621** [comment]
Sir, I would like to inform you that I have tried to resolve all the issues presented and I request you to check my issue again and reopen it .
Thank you

**Review by MohitGupta121 — COMMENTED** [review]
@Shubham6621 we already have Gym website.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
