### PR TITLE
[ADD]: CLIPBOARD LANDING PAGE ✨

### LINKED ISSUE #2020: [ADD]: CLIPBOARD LANDING PAGE 💡
**Describe the project you want to add with tech stack**
- The issue is about adding Clipboard Landing Page
- The site is fully responsive for all types of Devices, it was built with mobile first workflow

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
# Close #2020

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Respected @MohitGupta121, @pranjay-poddar please review this PR

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@0xabdulkhalid please don't upload directly too much large size files fetch or use them from cloud url such as 1st you upload your video in google drive or directly in Github, after that you get 1 link use that link in your project, not use directly images, videos files.
This increases the whole Dev-Greek project size.
Thanks!

**Comment by 0xabdulkhalid** [comment]
@MohitGupta121 there is no video i added, the whole project may size within 1mb

**Comment by MohitGupta121** [comment]
@0xabdulkhalid is not about the video, anything related to graphics such as images - png, jpg, svg, webp etc applicable to all.

**Comment by 0xabdulkhalid** [comment]
Done @MohitGupta121, You can verify now!

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
