### PR TITLE
added Rfooter

### LINKED ISSUE #1109: Responsive  Footer Design
A Fully Responsive  Footer Design using HTML,  CSS and JAVA SCRIPT . Will be very suitable for different types of personal websites or business websites. 
It is made fully responsive so that it can be easily used on any device. CSS's Flexbox has been used to make it responsive. With the help of Flexbox, no separate CSS code had to be added to make it responsive.
image

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Responsive Footer Design
Issue Number:  #1109

Close #1109

## Checklist
  - [x] I have mentioned the issue number in my Pull Request.
  - [x] I have commented on my code, particularly in hard-to-understand areas
  - [x] I have created a helpful and easy-to-understand README.md
  - [x] The footer design is responsive and works well on different devices.

## Description

   This pull request aims to enhance the footer design of the website. The changes include adding additional styling and 
   improving the accessibility of the links.

## Features

   1. Tested the footer on various screen sizes and devices to ensure responsiveness.
   2. Verified the accessibility of the links using automated accessibility testing tools.
   3. Manually checked the hover effects and responsiveness on different browsers.

## Changes Made

   1. Updated the HTML structure of the footer to include a more semantic layout.
   2. Added CSS classes to improve the responsiveness and visual styling of the footer.
   3. Modified the link colors and hover effects to enhance readability and user experience.
   4. Updated the Font Awesome library version to ensure compatibility and access to the latest icons.

Here are some video illustrations of the above-mentioned:

   1. Look at the Footer:
   

https://github.com/pranjay-poddar/Dev-Geeks/assets/129049677/91ced4a7-31bf-45f7-8fed-53f6365a5ce6

 ## Screenshots

    
Footer Design

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Fill up and follow the PR template and mention the issue number

**Comment by Kapileswar-Moharana** [comment]
> Fill up and follow the PR template and mention the issue number

Done @pranjay-poddar Sir can you please Check it

**Comment by Kapileswar-Moharana** [comment]
@pranjay-poddar Sir can you please check what to do next

**Review by Kapileswar-Moharana — COMMENTED** [review]
I have commented on my code, particularly in hard-to-understand areas

**Review by Millan-Kumar-Sahu — APPROVED** [review]
Works Properly

**Comment by Kapileswar-Moharana** [comment]
> Fill up and follow the PR template and mention the issue number

@pranjay-poddar Sir That I have filled up the PR template accordingly mentioning the Issue Number

**Pull request closed without merging**
