### PR TITLE
Added dark mode theme and change some style and added more products

### LINKED ISSUE #1514: Upgrading a project
I want to upgrade the responsive-product-component project to make the UI and the project design more attractive 
Please assign me under this issue under gssov'23 @pranjay-poddar

### PR DESCRIPTION
**Pull request by Soumyajit2825**
# Title and Issue number 

Upgrading a project #1514

Closes #1514 
# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

# Video

[screen-capture.webm](https://github.com/pranjay-poddar/Dev-Geeks/assets/100519291/210f795a-f86d-4601-9c63-32afbed45a91)

@pranjay-poddar please check and give me feedback if any more changes needed 
Thank You 😀

### CODE REVIEW

**Comment by Soumyajit2825** [comment]
@pranjay-poddar Have you checked it??

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Soumyajit2825 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Soumyajit2825** [comment]
@MohitGupta121 Check it now @pranjay-poddar

**Review by MohitGupta121 — APPROVED** [review]

**Comment by Soumyajit2825** [comment]
@MohitGupta121 Thanks 💘

**Pull request merged**
