### PR TITLE
Added the 3D Portfolio Website [GSSOC'23]

### LINKED ISSUE #4156: 3D Portfolio Website
**Describe the project you want to add with tech stack**
To add a visually appealing 3D portfolio website using ReactJs, Three.js ,React Three Fibre, Framer Motion library, tailwindcss.

**Expected behavior**
Professional Portfolio website to get hired.

### PR DESCRIPTION
**Pull request by Ayushkumargit7**
# Title and Issue number 
3D Portfolio Website

Issue #4156
Close #4156

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 @TusharKesarwani @pranjay-poddar 
Please review and merge the PR.
And add the gssoc23 label and level label.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Ayushkumargit7 Remove all the image from PR and upload it somewhere and then use it link in your project to load the image.

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 @pranjay-poddar @TusharKesarwani 
Please review and merge the PR.
And add the gssoc23 label and level label.

**Review by MohitGupta121 — COMMENTED** [review]
@Ayushkumargit7 still there

**Comment by Ayushkumargit7** [comment]
@MohitGupta121 @pranjay-poddar @TusharKesarwani 
i deleted the images , i think you are talking about the files in public folder , they are the 3D models used in the project , we can't delete them.

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Ayushkumargit7 remove all images from PR and use them by link to load

**Pull request closed without merging**
