### PR TITLE
completed task  water sort puzzle game

### PR DESCRIPTION
**Pull request by payalpm**
# Title and Issue number 

Close #<issue_no>

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by payalpm** [comment]
Where i will check

**Comment by pranjay-poddar** [comment]
Follow and fill up the PR template and mention the issue number

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
.

**Comment by payalpm** [comment]
Ok i will

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@payalpm Please move your whole project to their respective project folder as mention in [repo](https://github.com/pranjay-poddar/Dev-Geeks/pull/2005).

**Pull request closed without merging**
