### PR TITLE
made changes in btech chai wala website

### PR DESCRIPTION
**Pull request by Harshita1010**
# made changes in btech chai wala

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented on my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by devasyarajguru** [comment]
What are this review required , all checks failed errors ??  I am a beginner.

**Comment by Saurabh-kumar09** [comment]
@Harshita1010 Please mention the issue number as close #issue_your_issue_number. Then I can review your PR.

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Remove merge conflicts and also follow and fill up the PR template correctly

**Comment by MohitGupta121** [comment]
Closing as part of GSSOC 2022 and now outdated.

**Pull request closed without merging**
