### PR TITLE
Add Auto WebScrapping Python Project

### LINKED ISSUE #1324: [GSSoc'23] Auto Web Scrapping
**Describe the project you want to add with tech stack**
I want to add an auto web scrapping project using Python technology.

**Expected behavior**
I will be using Python as the programming language to code the Project and will thereby stack the resourceful space on the project store of tech stack.

**Screenshots (optional)**

**Additional context (optional )**
I would love to add features if asked in the respective Project as well.

Please assign me this project for Auto Web-scrapper.

You can go through my LinkedIn and Github to assure the project's genuineness ---
GitHub - https://github.com/s4shantanu
LinkedIn - https://www.linkedin.com/in/shantanu-raut

### PR DESCRIPTION
**Pull request by s4shantanu**
# Title and Issue number 
[GSSoc'23] Auto Web Scrapping  issue number #1324 

Close #<issue_no>
Close #1324 

# Checklist:

[] I have mentioned the issue number in my Pull Request.
[] I have commented my code, particularly in hard-to-understand areas
[] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by s4shantanu** [comment]
Hello, @Ashutosh0120 @rachit98 @prateekj7777 Please review my PR and merge it.
Thank You <3

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@s4shantanu please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Ashutosh0120** [comment]
> Hello, @Ashutosh0120 @rachit98 @prateekj7777 Please review my PR and merge it. Thank You <3

I am not the Project admin.

**Comment by s4shantanu** [comment]
@mohit sure

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@s4shantanu please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by MohitGupta121** [comment]
inactive

**Pull request closed without merging**
