### PR TITLE
added sorting visualizer in js-projects directory

### LINKED ISSUE #662: Sorting Visualizer
- I have an exciting sorting visualizer app which I created during my college days
- It has functionality for 5 most important day-to-day sorting algorithms
- I want to share with the community for everyone to gain help
- I think it will be a great feature to have as a part of this project

**@pranjay-poddar Please assign me this issue. Thanks in Advance!**

### PR DESCRIPTION
**Pull request by D-Anir**
### Title And Issue Number

Sorting Visualizer #662 
Close #662 

### CheckList:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### Sorting Visualizer Web App

**Tech Stack**
- Used Vanilla JS for building all the sorting algorithms' logic
- HTML5 for the UI of the app

**Features**
- Generate an array of 20 random integers any number of times
- Choose between 5 sorting algorithms to see how they perform in terms of speed to sort the given array
- If you think the sorting is taking too long, you can adjust the speed manually with 6 different speeds

**Screenshots**

Initially:

Screenshot (307)

Finally (Using Insertion Sort):

Screenshot (496)

**Thanks & Regards**

### CODE REVIEW

**Comment by D-Anir** [comment]
@pranjay-poddar 
Can you review this PR?
Thanks & Regards!

**Review by pranjay-poddar — APPROVED** [review]

**Comment by pranjay-poddar** [comment]
follow the PR template

**Comment by D-Anir** [comment]
> follow the PR template

Hi, can you tell where can I find the PR template?
Thanks!

**Comment by D-Anir** [comment]
Hi @pranjay-poddar ,
Is this repo excluded from hacktoberfest? I submitted a PR in this repo, it was under the review stage. Now it's showing excluded. Can you help me with this?
Thanks in Advance.

**Pull request merged**
