### PR TITLE
Added Spider Man Game

### PR DESCRIPTION
**Pull request by SyedImtiyaz-1**
Hello Project Admin,
## Screenshot -
Screenshot from 2023-06-23 02-30-33

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### It is super ready to `Merge`

### CODE REVIEW

**Comment by SyedImtiyaz-1** [comment]
Hello @TusharKesarwani ,
please review this one.

**Comment by SyedImtiyaz-1** [comment]
Hello @TusharKesarwani ,
Kindly review this 👍🏻

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@SyedImtiyaz-1 same for this images must used from links and not uploaded in the PR.

**Comment by SyedImtiyaz-1** [comment]
@MohitGupta121 ,
Check now I have added drive links instead of  images.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@SyedImtiyaz-1 please resolve conflicts then it's ready to merge

**Comment by SyedImtiyaz-1** [comment]
@MohitGupta121 ,
It is ready to `merge` 👍🏻

**Review by MohitGupta121 — APPROVED** [review]

**Comment by killer2O** [comment]
@MohitGupta121 @pranjay-poddar this was already merged in another project https://github.com/kunjgit/GameZone/pull/2160 and https://github.com/GameSphere-MultiPlayer/GameSphere/pull/601

**Comment by SyedImtiyaz-1** [comment]
> @MohitGupta121 @pranjay-poddar this was already merged in another project [kunjgit/GameZone#2160](https://github.com/kunjgit/GameZone/pull/2160) and [GameSphere-MultiPlayer/GameSphere#601](https://github.com/GameSphere-MultiPlayer/GameSphere/pull/601)

so, what's the matter bro ?

**Comment by killer2O** [comment]
@MohitGupta121 @Saurabh-kumar09 @pranjay-poddar Please remove the labels and mark this as spam as this very unfair to other contributers. Many other contributers are doing the same thing. Please take appropriate actions

**Comment by SyedImtiyaz-1** [comment]
Let me clear the point, 
It's not about the addition of the project it's my own game and it is approved by the admin so I think no one can enter between our talks. 
and Mr. Killer I saw your real profile too you're doing this because we both have same points so please do contribution by your own don't do this silly stuff if you're not a kid okay ?
& one more thing there is no mention about the contribution. We can contribute any in any tech stack we're comfortable in and it is allowed in GSSOC-23 it's just a friendly game for the users but you @killer2O making this is an issue.
So first check the guidelines as per GSSOC-23 then say anything you want.

**Comment by SyedImtiyaz-1** [comment]
> @MohitGupta121 @Saurabh-kumar09 @pranjay-poddar Please remove the labels and mark this as spam as this very unfair to other contributers. Many other contributers are doing the same thing. Please take appropriate actions

Also I'm not spamming same game in the same project or repo. it legal.
Please go through the guidelines then contribute.

**Comment by Killer2OP** [comment]
> > @MohitGupta121 @Saurabh-kumar09 @pranjay-poddar Please remove the labels and mark this as spam as this very unfair to other contributers. Many other contributers are doing the same thing. Please take appropriate actions
> 
> Also I'm not spamming same game in the same project or repo. it legal. @killer2O Please go through the guidelines then contribute & you can here with a fake ID & I think this is unfair. am I right @MohitGupta121 ?
> 
> ### his real ID : @Killer2OP

Bro You can contact to guri as well any of team member you are no one to me whom I'll give explanation team member take care of everything the way you are raising your rank

**Comment by Killer2OP** [comment]
@SyedImtiyaz-1 kuch pta nhi h to faltu bole mat na kese ko blame kar jake mod se contact kr itna faltu ni hu mai jo ye stupid harkate karu acha hoga apne kam se kam rakhe

**Comment by SyedImtiyaz-1** [comment]
> @SyedImtiyaz-1 kuch pta nhi h to faltu bole mat na kese ko blame kar jake team member se contact kr itna faltu ni hu mai jo ye stupid harkate karu acha hoga apne kam se kam rakhe

Same goes to you @killer2O

**Comment by gurjeetsinghvirdee** [comment]
Now I had a doubt that this game was yours: __https://github.com/RedEdge967/Spider-Man__

Remove the labels bro @MohitGupta121

**Comment by SyedImtiyaz-1** [comment]
@gurjeetsinghvirdee  My game is not same as this you can play the game I learnt this game in a online course and its my own work then how this all stuff for me ?
I added the drive files all task is proper maintained and there is more games like snake mario and all which are repeating then why only me ? because I give my 100% and developed this by now own or just for this killer2op objection ???

**Comment by gurjeetsinghvirdee** [comment]
For your info already blacklisted some of the contributors from leaderboard, I don't have time to check these things, this is the work of maintainers to check the PR, like you said you learnt online then do some own changes why are you copying the whole content, what if others contributors will say same like this & ranking on 1st then it will be ok for you & why are you spamming on different repos to make extra points, please check server rules.

**Comment by SyedImtiyaz-1** [comment]
> For your info already blacklisted some of the contributors from leaderboard, I don't have time to check these things, this is the work of maintainers to check the PR, like you said you learnt online then do some own changes why are you copying the whole content, what if others contributors will say same like this & ranking on 1st then it will be ok for you & why are you spamming on different repos to make extra points, please check server rules.

Sure @gurjeetsinghvirdee no problem.
will be more careful from the next time.
@MohitGupta121 remove the lables will add different thing expect this now. 
## Thank You.

**Comment by SyedImtiyaz-1** [comment]
> > > For your info already blacklisted some of the contributors from leaderboard, I don't have time to check these things, this is the work of maintainers to check the PR, like you said you learnt online then do some own changes why are you copying the whole content, what if others contributors will say same like this & ranking on 1st then it will be ok for you & why are you spamming on different repos to make extra points, please check server rules.
> > 
> > 
> > Sure @gurjeetsinghvirdee no problem. will be more careful from the next time. @MohitGupta121 remove the lables will add different thing except this now.
> > ## Thank You.
> 
> ## Yes be careful! I will be on lookout for you 😈😈

## No Problem will see you in the leaderboard.

**Comment by gurjeetsinghvirdee** [comment]
If you do these things here in others repo, I will ban you both. 

@killer2O @SyedImtiyaz-1

**Comment by SyedImtiyaz-1** [comment]
Really Sorry @gurjeetsinghvirdee 
But he is just doing too much.
Will be careful and I'm not going to reply on his any action now 
Really Sorry

**Comment by SyedImtiyaz-1** [comment]
@Killer2-O But you're not a part of GSSoC 23 and I did this earlier by youtube course and I have canceled the all the PR which I have made so whats the issue now. 
@gurjeetsinghvirdee you can report this guy.
He is targeting me and just stalking me with a new ID now. 
Previously his ID was Killer2O and now he came up with Killer2-O
#help

**Comment by SyedImtiyaz-1** [comment]
> lets talk on discord. give me ur discord id

give me your I'll add you.

**Pull request merged**
