### PR TITLE
Added reset password option in existing PHP project (User Signup and Login)

### LINKED ISSUE #2897: Including password reset option using email to existing PHP project
**Describe the Feature you want to end**
Including password reset option using email to existing PHP project

**Expected behavior**

People can reset their password in case they forgot.

### PR DESCRIPTION
**Pull request by iamvittaln**
# Title and Issue number 

Title: Including password reset option using email to existing PHP project
Issue Number: #2897

Close #2897

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by iamvittaln** [comment]
Dear Sir, @pranjay-poddar @Saurabh-kumar09 @MohitGupta121 @TusharKesarwani
I couldn't work on this issue due to college works. The whole day (Sunday, 06/08/2023), I completely worked upon this and added a complex issue (resetting password in database) as a feature to the existing PHP project. As the GSSoC'23 is going to end, I kindly request you to accept this PR as soon as possible and give this feature a higher level (just a request, a lot has been worked upon this feature) so that I get more points.

**Comment by iamvittaln** [comment]
@MohitGupta121 Sir kindly accept this pull request as soon as possible, as the coding period is going to end very soon.
Kindly close this issue #2897 with pull request number #4931.

Thanking you in advance,
Vittal N

**Comment by iamvittaln** [comment]
@MohitGupta121 Sir kindly accept this pull request as soon as possible, as the coding period is going to end very soon.
Kindly close this issue https://github.com/pranjay-poddar/Dev-Geeks/issues/2897 with pull request number https://github.com/pranjay-poddar/Dev-Geeks/pull/4931.

Thanking you in advance,
Vittal N

**Comment by iamvittaln** [comment]
Dear Sir, @pranjay-poddar @MohitGupta121 @TusharKesarwani,

README.md file was missing in my PR. Now I have added and updated it too. Kindly review it. The coding period is going to end soon sir, please accept my PR.

**Review by TusharKesarwani — APPROVED** [review]

**Comment by iamvittaln** [comment]
@TusharKesarwani Thankyou so much for merging the pull request. But I request you to assign level 2/level 3 for this PR please. A lot of backend work has been done to change the password in the database. You can check the same by cloning the project. Kindly update the level so that I get more points.

**Comment by iamvittaln** [comment]
@pranjay-poddar @MohitGupta121 @TusharKesarwani Kindly update the level that is assigned to this PR sir

**Pull request merged**
