### PR TITLE
code basketballgame #2976

### LINKED ISSUE #2976: Basketball Game
**Describe the project you want to add with tech stack**

It has a basket at a fixed position and a ball is given at various angles at various times. The player has to throw the ball into the basket and earn points. I will be using HTML ,CSS,JS

**Expected behavior**

Everytime the player accurately throws the ball into the basket, he earns 1 point.

**Screenshot**

Screenshot 2023-07-04 103843

### PR DESCRIPTION
**Pull request by Vyshnavi21504**
# Title and Issue number 

Basketball_game #2976 

Close #2976 

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Vyshnavi21504** [comment]
I have completed this issue  .pls merge it @MohitGupta121

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Vyshnavi21504 remove all images from PR and upload them somewhere else then use from there link to fetch load the images.

**Comment by Vyshnavi21504** [comment]
@MohitGupta121 how to do it?

**Comment by MohitGupta121** [comment]
Upload it anywhere and use images link instead of image path in src, for more see merged PR.

**Pull request closed without merging**
