### PR TITLE
Typing_Speed_Game

### LINKED ISSUE #2143: [GSSoC'23] : Typing Speed Test
**Describe the project you want to add with tech stack**
A typing speed test game is a  website that measures and evaluates a player's typing speed and accuracy. It typically presents the player with a random set of words, phrases, or sentences that they need to type accurately within a certain time limit.

**Expected behavior**

- The player clicks the start button to initiate the game. 
- A random text snippet or set of words is displayed for the player to type.
- As the player types, their input is compared to the expected text for accuracy.
- Real-time feedback may be provided, such as highlighting correct and incorrect characters or words.
- It will display time taken , typing speed(words per minute) and accuracy of the user

**Screenshots (optional)**

**Additional context (optional )**

### PR DESCRIPTION
**Pull request by vaibhavi-d18**
# Title and Issue number 
#2143
Typing Speed Test Game using HTML , CSS , JS

Close #2143

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

Link:  https://vaibhavi-d18.github.io/Typing_Speed_Test_Game/

### CODE REVIEW

**Comment by vaibhavi-d18** [comment]
@pranjay-poddar can you please add GSSoC'23 label to this issue

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@vaibhavi-d18 please use PR template and link issue with it

**Comment by vaibhavi-d18** [comment]
> @vaibhavi-d18 please use PR template and link issue with it

@MohitGupta121  
Thank you for your feedback on my pull request. I apologize for the confusion, but I'm still unsure about how to use the PR template and link the issue with it. I would greatly appreciate it if you could provide me a way that is more accessible for me to follow.

**Comment by MohitGupta121** [comment]
@vaibhavi-d18 just proper close #issue_number to link pr with issue

**Comment by vaibhavi-d18** [comment]
> @vaibhavi-d18 just proper close #issue_number to link pr with issue

@MohitGupta121 
I have made the desired changes , please check once

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
