### PR TITLE
Flights and hotel rooms booking website

### LINKED ISSUE #1730: [GSSoC'23]Flight and hotel room booking website
**Describe the project you want to add with tech stack**
To create a clone of a flight and hotel room booking website using HTML, CSS and JS

**Expected behavior**
Fully responsive and a functional website

### PR DESCRIPTION
**Pull request by Sreenija03**
This website is a clone of the agoda website created using HTML,CSS,js

Close Issue Number #1730

Screenshot 2023-06-07 at 6 40 14 PM
Screenshot 2023-06-07 at 6 40 39 PM

# Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Sreenija03** [comment]
Can you please review the PR @Saurabh-kumar09 @pranjay-poddar

**Review by MohitGupta121 — COMMENTED** [review]
@Sreenija03 LGTM, Thanks!

**Review by MohitGupta121 — APPROVED** [review]

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Sreenija03 please add screen recording for your changes in PR description so that it's easy for Reviewer to review the PR. Thanks!

**Comment by Sreenija03** [comment]
@MohitGupta121 I have added the screen recording ,can you please check
https://github.com/pranjay-poddar/Dev-Geeks/assets/119659973/413fb571-6dcf-4fec-a1c3-c0bfd0c2aea7

**Review by MohitGupta121 — APPROVED** [review]
@Sreenija03 Thanks, LGTM

**Pull request merged**
