### PR TITLE
Testimonial Grid Section

### LINKED ISSUE #1954: Testimonial Grid Section
**Describe the project you want to add with tech stack**

Testimonial Grid Section using HTML and CSS in Frontend-Projects 

## Issue Type:
- [x] New Project

**Screenshots**
desktop-preview

### PR DESCRIPTION
**Pull request by MisterMickey**
# Testimonial Grid Section

Close #1954 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

desktop-preview

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
Resolve branch conflicts

**Comment by MisterMickey** [comment]
@pranjay-poddar Resolved.

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Project wrongly added in readme

**Comment by MisterMickey** [comment]
@pranjay-poddar On which number should I add my project?

**Comment by MisterMickey** [comment]
@pranjay-poddar This can't be merged?

**Pull request closed without merging**
