### PR TITLE
Made a Timer Using Tkinter and Python

### LINKED ISSUE #403: Stopwatch using python
**Describe the project you want to add with tech stack**
    a stopwatch in python

Screenshot 2022-08-06 110027

### PR DESCRIPTION
**Pull request by srummanf**
# Stopwatch using Python 403 

Close #<issue_no>

# Checklist:

- [yes] I have mentioned the issue number in my Pull Request.
- [not necessary] I have commented my code, particularly in hard-to-understand areas
- [no] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by pranjay-poddar** [comment]
fill the PR template

**Comment by srummanf** [comment]
filled

**Comment by srummanf** [comment]
is it conflicting or should i wait

**Review by pranjay-poddar — APPROVED** [review]

**Comment by srummanf** [comment]
Respected sir
I uploaded a PR on space game using Pygame and it's working fine, can you
please merge the pr or give solution
The details are in the PR as per as the guidelines

**Pull request merged**
