### PR TITLE
#3744 LOVE symbol generator by Python

### LINKED ISSUE #3744: LOVE design using python
**Describe the project you want to add with tech stack**
a python turtle generated project

**Expected behavior**

**Screenshots (optional)**

**Additional context (optional )**
pls assign me the task

### PR DESCRIPTION
**Pull request by shubha987**
Love symbol generator #3744 

Close #3744 

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by shubha987** [comment]
@pranjay-poddar please review and merge it

**Comment by jaivsh** [comment]
What the heck sort of a project is this!

**Comment by shubha987** [comment]
@MohitGupta121 pls merge it

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@shubha987 why you uploading 2 projects in your PR, only upload 1 project related to your Issue.

**Comment by shubha987** [comment]
@MohitGupta121 sorry!! i have deleted other two files only #3749 is there

**Comment by MohitGupta121** [comment]
@shubha987 so resolve them I need proper clean folder for project.

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
PTAL

**Comment by shubha987** [comment]
ok i am done with the mess @MohitGupta121

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@shubha987 still there please add your project in proper folder

**Comment by shubha987** [comment]
@MohitGupta121  ya updated with proper folder. pls merge it.

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
