### PR TITLE
Create Gym-Website

### LINKED ISSUE #1982: Improve About section of Apna Gym
The about section can look more attractive by adding some features like:
ORIGINAL:
about-original
My design:
about-myDesign
Could you please raise an issue and assign it to me under GSSoC'23

### PR DESCRIPTION
**Pull request by BhartiNagpure**
#1982  Improve the about section

Close #1982

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Saurabh-kumar09** [comment]
@BhartiNagpure you haven't committed the code files which you changed. Add those files.

**Comment by BhartiNagpure** [comment]
@Saurabh-kumar09  I already commited the code files and also add those files  into the #1982 issue.

**Comment by BhartiNagpure** [comment]
@Saurabh-kumar09 committed the code files please go through it.

**Comment by pranjay-poddar** [comment]
@BhartiNagpure code is not committed, please watch some YouTube videos on GitHub commit, hope this helps

**Comment by pranjay-poddar** [comment]
> @Saurabh-kumar09 committed the code files please go through it.
> 



Added a screenshot of your committed files

**Pull request closed without merging**
