### PR TITLE
Added Translator Website

### PR DESCRIPTION
**Pull request by dalalsoham**
# Title and Issue number 

Close #<issue_no>

# Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Review by pranjay-poddar — CHANGES_REQUESTED** [review]
Mention issue number and move project to js projects folder

**Comment by MohitGupta121** [comment]
Inactive

**Comment by dalalsoham** [comment]
this is not a inactive project

**Comment by MohitGupta121** [comment]
@dalalsoham please make new proper PR and work accordingly

**Comment by dalalsoham** [comment]
@MohitGupta121 can you said me how to find issue no ?

**Comment by MohitGupta121** [comment]
issue number you get from url of Issue after "/"

**Pull request closed without merging**
