### PR TITLE
[Game] : Maxico Escape

### PR DESCRIPTION
**Pull request by Durgesh4993**
# Title and Issue number 

Close ##1933

# Checklist:

- [] I have mentioned the issue number in my Pull Request.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`

### CODE REVIEW

**Comment by Durgesh4993** [comment]
Demo vedio:

https://github.com/pranjay-poddar/Dev-Geeks/assets/98798977/32c7f83a-d52a-4405-bf07-abd487937691

**Comment by Durgesh4993** [comment]
@MohitGupta121 Please review the code mow there are no image i have uploded all image then i have used their

**Review by MohitGupta121 — CHANGES_REQUESTED** [review]
@Durgesh4993 please remove all assets videos/images files from PR and use them through link in your project. Thanks.

**Comment by Durgesh4993** [comment]
Ok sir

**Review by MohitGupta121 — APPROVED** [review]

**Pull request merged**
