### PR TITLE
Night Owl with toggle  

### PR DESCRIPTION
**Pull request by ElvinPero**
# Adding dark mode to the site #859

# Checklist:

- [YES] I have mentioned the issue number in my Pull Request.
- [YES] I have added the retain theme functionality as discussed in my issue.
image
image

### CODE REVIEW

**Comment by ElvinPero** [comment]
@pranjay-poddar I have made the night mode toggler for website.
Kindly review this PR

**Comment by ElvinPero** [comment]
> Follow the PR template

Ok

**Comment by ElvinPero** [comment]
> Follow the PR template
I cannot find the PR template @pranjay-poddar . Can you reshare it please.

**Comment by pranjay-poddar** [comment]
> > Follow the PR template
> I cannot find the PR template @pranjay-poddar . Can you reshare it please.
> 

Make a new pr

**Pull request closed without merging**
